/**
 * Evidence Sheet Builders (Prompt 305)
 * Helper functions to construct standardized sheets for evidence workbooks.
 */

import * as XLSX from 'xlsx';
import type {
  WorkbookReadmeMeta,
  ExecutiveSummaryRow,
  CalculationBridgeRow,
  FinancialCheckRow
} from '../types/evidenceWorkbook';
import {
  EVIDENCE_README_MANDATORY_NOTICE,
  EVIDENCE_README_WARNING
} from '../constants/evidenceWorkbook';

export class EvidenceSheetBuilders {
  /**
   * Creates the mandatory 01_README sheet
   */
  public static createReadmeSheet(meta: WorkbookReadmeMeta): XLSX.WorkSheet {
    const readmeData = [
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Customer Name', 'Detail': meta.customerName },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Analysis Run ID', 'Detail': meta.analysisRunId },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Data Version ID', 'Detail': meta.dataVersionId },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Report Version ID', 'Detail': meta.reportVersionId || 'N/A (Pre-submission)' },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Module / Subject', 'Detail': meta.moduleName },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Generated Timestamp', 'Detail': meta.generatedAt },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Generated By', 'Detail': meta.generatedBy },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Calculation Engine Version', 'Detail': meta.calculationVersion },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Source Record Count', 'Detail': String(meta.sourceRecordCount) },
      { 'Section': 'WORKBOOK GOVERNANCE', 'Attribute': 'Total Source Spend', 'Detail': `₹${meta.totalSourceSpendCr.toFixed(2)} Cr` },
      { 'Section': 'MANDATORY NOTICE', 'Attribute': 'Evidence Authority', 'Detail': EVIDENCE_README_MANDATORY_NOTICE },
      { 'Section': 'MANDATORY NOTICE', 'Attribute': 'Forensic Warning', 'Detail': EVIDENCE_README_WARNING },
      { 'Section': 'PURPOSE & INSTRUCTIONS', 'Attribute': 'Primary Purpose', 'Detail': meta.purpose },
      { 'Section': 'PURPOSE & INSTRUCTIONS', 'Attribute': 'Validation Steps', 'Detail': meta.validationInstructions },
      ...Object.entries(meta.importantDefinitions).map(([kpi, def]) => ({
        'Section': 'KPI DEFINITIONS',
        'Attribute': kpi,
        'Detail': def
      }))
    ];

    return XLSX.utils.json_to_sheet(readmeData);
  }

  /**
   * Creates the 02_EXECUTIVE_SUMMARY sheet
   */
  public static createExecutiveSummarySheet(rows: ExecutiveSummaryRow[]): XLSX.WorkSheet {
    return XLSX.utils.json_to_sheet(rows);
  }

  /**
   * Creates the 03_CALCULATION_BRIDGE sheet
   */
  public static createCalculationBridgeSheet(rows: CalculationBridgeRow[]): XLSX.WorkSheet {
    return XLSX.utils.json_to_sheet(rows);
  }

  /**
   * Creates the financial checks sheet
   */
  public static createFinancialChecksSheet(rows: FinancialCheckRow[]): XLSX.WorkSheet {
    return XLSX.utils.json_to_sheet(rows);
  }

  /**
   * Creates an audit trail sheet
   */
  public static createAuditTrailSheet(events: Array<{
    'Timestamp': string;
    'User': string;
    'Action': string;
    'Data Version': string;
    'Report Version': string;
    'Status': string;
  }>): XLSX.WorkSheet {
    return XLSX.utils.json_to_sheet(events);
  }
}
