/**
 * PCBI Platform Integration Portfolio Fixtures
 */

import type { Module4InputContractRecord } from '../types/pcbiPlatformIntegration';

export const CONTROLLED_PORTFOLIO_SCENARIOS: Record<string, Module4InputContractRecord> = {
  'Scenario A — Production-ready PCBI': {
    transactionId: 'TX-SCN-A',
    customerActualPrice: 720000,
    customerUnit: 'MT',
    customerCurrency: 'INR',
    customerDate: '2026-06-15',
    module2Classification: 'Copper Wire Rods 8mm EC Grade',
    unspsc: '30102100',
    pcbiId: 'PCBI-IND-MET-COP-001',
    pcbiIndex: 128.4,
    pcbiBenchmarkValue: 660000,
    pcbiSource: 'MCX / LME Cash Settlement',
    pcbiMethodology: 'MONTHLY_WEIGHTED_AVERAGE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_AVAILABLE',
    pcbiUnit: 'MT',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-A'
  },
  'Scenario B — Partial-history PCBI': {
    transactionId: 'TX-SCN-B',
    customerActualPrice: 850,
    customerUnit: 'PIECE',
    customerCurrency: 'INR',
    customerDate: '2026-06-10',
    module2Classification: 'Tungsten Carbide Inserts',
    unspsc: '23241600',
    pcbiId: 'PCBI-IND-MET-TCI-001',
    pcbiIndex: null,
    pcbiBenchmarkValue: null,
    pcbiSource: 'Tooling Index Bulletin',
    pcbiMethodology: 'MONTHLY_OFFICIAL_INDEX',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_PARTIAL',
    pcbiUnit: 'PIECE',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-B'
  },
  'Scenario C — Missing PCBI commodity': {
    transactionId: 'TX-SCN-C',
    customerActualPrice: 1425000,
    customerUnit: 'MT',
    customerCurrency: 'INR',
    customerDate: '2026-06-12',
    module2Classification: 'Ferro Molybdenum 65%',
    unspsc: '30102900',
    pcbiId: 'PCBI-IND-MET-FMO-001',
    pcbiIndex: null,
    pcbiBenchmarkValue: null,
    pcbiSource: 'UNVERIFIED',
    pcbiMethodology: 'PENDING',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_MISSING',
    pcbiUnit: 'MT',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-C'
  },
  'Scenario D — Specification mismatch': {
    transactionId: 'TX-SCN-D',
    customerActualPrice: 185,
    customerUnit: 'LTR',
    customerCurrency: 'INR',
    customerDate: '2026-06-18',
    module2Classification: 'Industrial Hydraulic Oil ISO 68',
    unspsc: '15121500',
    pcbiId: 'PCBI-IND-LUB-SPEC_MISMATCH-001',
    pcbiIndex: 110.0,
    pcbiBenchmarkValue: 170,
    pcbiSource: 'Lubricant Index',
    pcbiMethodology: 'MONTHLY_AVERAGE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_BLOCKED',
    pcbiUnit: 'LTR',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-D'
  },
  'Scenario E — Unit mismatch': {
    transactionId: 'TX-SCN-E',
    customerActualPrice: 12500,
    customerUnit: 'ROLL',
    customerCurrency: 'INR',
    customerDate: '2026-06-20',
    module2Classification: 'Heavy Conveyor Belting',
    unspsc: '24101700',
    pcbiId: 'PCBI-IND-BEL-001',
    pcbiIndex: 115.0,
    pcbiBenchmarkValue: 11000,
    pcbiSource: 'Belt Index',
    pcbiMethodology: 'MONTHLY_AVERAGE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_BLOCKED',
    pcbiUnit: 'MT',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-E'
  },
  'Scenario F — Currency mismatch': {
    transactionId: 'TX-SCN-F',
    customerActualPrice: 45000,
    customerUnit: 'UNIT',
    customerCurrency: 'INR',
    customerDate: '2026-06-22',
    module2Classification: 'Imported Specialty Flanges',
    unspsc: '40173300',
    pcbiId: 'PCBI-IMP-FLG-001',
    pcbiIndex: 120.0,
    pcbiBenchmarkValue: 420,
    pcbiSource: 'European Flange Index',
    pcbiMethodology: 'MONTHLY_AVERAGE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_BLOCKED',
    pcbiUnit: 'UNIT',
    pcbiCurrency: 'GBP',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-F'
  },
  'Scenario G — Geography mismatch': {
    transactionId: 'TX-SCN-G',
    customerActualPrice: 38000,
    customerUnit: 'MT',
    customerCurrency: 'INR',
    customerDate: '2026-06-24',
    module2Classification: 'Foundry Pig Iron',
    unspsc: '30102400',
    pcbiId: 'PCBI-GLB-PIG-001',
    pcbiIndex: 118.0,
    pcbiBenchmarkValue: 36000,
    pcbiSource: 'Global CFR Feed',
    pcbiMethodology: 'MONTHLY_AVERAGE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_BLOCKED',
    pcbiUnit: 'MT',
    pcbiCurrency: 'INR',
    pcbiGeography: 'GLOBAL_CFR',
    provenanceReference: 'PROV-TX-SCN-G'
  },
  'Scenario H — Frequency mismatch': {
    transactionId: 'TX-SCN-H',
    customerActualPrice: 42000,
    customerUnit: 'MT',
    customerCurrency: 'INR',
    customerDate: '2026-06-25',
    module2Classification: 'Stainless Steel Scrap',
    unspsc: '30103000',
    pcbiId: 'PCBI-IND-SCR-001',
    pcbiIndex: 112.0,
    pcbiBenchmarkValue: 40000,
    pcbiSource: 'Daily Scrap Feed',
    pcbiMethodology: 'FREQ_MISMATCH_DAILY',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_BLOCKED',
    pcbiUnit: 'MT',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-H'
  },
  'Scenario I — Not-benchmarkable service': {
    transactionId: 'TX-SCN-I',
    customerActualPrice: 250000,
    customerUnit: 'MONTH',
    customerCurrency: 'INR',
    customerDate: '2026-06-30',
    module2Classification: 'Plant Security & Canteen Services',
    unspsc: '92121500',
    pcbiId: 'PCBI-SRV-SEC-001',
    pcbiIndex: null,
    pcbiBenchmarkValue: null,
    pcbiSource: 'NONE',
    pcbiMethodology: 'NONE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_NOT_BENCHMARKABLE',
    pcbiUnit: 'MONTH',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-I'
  },
  'Scenario J — Newly added dynamic PCBI': {
    transactionId: 'TX-SCN-J',
    customerActualPrice: 195000,
    customerUnit: 'MT',
    customerCurrency: 'INR',
    customerDate: '2026-06-28',
    module2Classification: 'Custom Ingested Ingot feed',
    unspsc: '30101800',
    pcbiId: 'PCBI-DYN-ING-001',
    pcbiIndex: 114.2,
    pcbiBenchmarkValue: 182000,
    pcbiSource: 'Admin Approved Custom Feed',
    pcbiMethodology: 'MONTHLY_WEIGHTED_AVERAGE',
    pcbiEffectiveDate: '2026-06',
    pcbiStatus: 'PCBI_AVAILABLE',
    pcbiUnit: 'MT',
    pcbiCurrency: 'INR',
    pcbiGeography: 'INDIA_DOMESTIC',
    provenanceReference: 'PROV-TX-SCN-J'
  }
};
