/**
 * Executive Brief Master Opportunity Register Constants
 * Conforming strictly to Section 2, Section 14, Section 15, Section 19, and Section 22 of Prompt 274.
 */

import type { ExecutiveBriefMasterOpportunityItem } from '../types';

export const EXECUTIVE_BRIEF_MASTER_OPPORTUNITIES: readonly ExecutiveBriefMasterOpportunityItem[] = [
  {
    opportunityId: 'OPP-001',
    module: 'Module 2',
    analysis: 'Vendor Consolidation',
    category: 'Industrial Supplies & MRO',
    item: 'Fasteners, Bearings & Plant Spares',
    supplier: '912 Tail & Regional Vendors',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹154.20 Cr',
    valueType: 'DIRECT_PROCUREMENT_SAVING',
    valueTypeLabel: 'Direct Procurement Opportunity',
    lowPercent: '3.0%',
    basePercent: '4.0%',
    highPercent: '5.0%',
    lowValue: '₹4.63 Cr',
    baseValue: '₹6.17 Cr',
    highValue: '₹7.71 Cr',
    indicativeOpportunity: '₹4.63 – ₹7.71 Cr (Base: ₹6.17 Cr)',
    confidence: 'High (Verified Transaction Dispersion)',
    dataEvidence: '12,480 line items across 912 vendors showing 28% price variance on identical SKUs.',
    calculation: 'Eligible Spend ₹154.20 Cr × Planning Leverage (3%–5%) = ₹4.63–₹7.71 Cr',
    assumption: 'Volume bundling across 4 preferred regional partners yields 4% baseline price concession.',
    executionMechanism: 'Consolidated RFQ & Bilateral Negotiation (E-auction qualifying for standard fasteners)',
    overlapGroup: 'GRP-A (Tail & Vendor Consolidation)',
    exclusionStatus: 'Included (Zero Overlap in GRP-A)',
    owner: 'Procurement Category Lead',
    timeline: '90 Days (Phase 1)',
    status: 'Ready for RFP',
    background: 'Supplier fragmentation identified across 912 micro-vendors supplying plant MRO.',
    objective: 'Aggregate fragmented volumes to capture tier-1 volume discounts and contract rate parity.',
    finding: '912 tail vendors represent ₹154.20 Cr of eligible addressable spend with high price dispersion.',
    valueOpportunity: 'Low: ₹4.63 Cr (3%), Base: ₹6.17 Cr (4%), High: ₹7.71 Cr (5%) indicative volume leverage.',
    executionApproach: 'Issue unified RFP to top 4 distributors with master price book and quarterly rebates.',
    nextStep: 'Segment suppliers → issue consolidated RFQ → negotiate volume tiers → award preferred contracts.',
    validationRequired: 'Signed distributor contract rate cards and ERP catalog enablement.',
    classificationLabel: 'PLANNING ASSUMPTION',
    transactionSampleId: 'TX-MRO-88219'
  },
  {
    opportunityId: 'OPP-002',
    module: 'Module 2',
    analysis: 'PO Consolidation / Process Productivity',
    category: 'All Addressable Categories',
    item: 'Purchase Orders < ₹2.5 Lakhs',
    supplier: 'Cross-Supplier Transaction Flow',
    customerSpendBase: '₹4,931.00 Cr (4,120 POs)',
    eligibleSpend: '3,296 Target POs',
    valueType: 'PROCESS_PRODUCTIVITY_BENEFIT',
    valueTypeLabel: 'Process Productivity Benefit',
    lowPercent: '15.0%',
    basePercent: '20.0%',
    highPercent: '25.0%',
    lowValue: '618 POs',
    baseValue: '824 POs',
    highValue: '1,030 POs',
    indicativeOpportunity: '20% PO Volume Reduction (824 POs saved, Direct Spend: ₹0.00 Cr)',
    confidence: 'High (ERP PO Velocity Audit)',
    dataEvidence: '4,120 annual POs generated with 42% micro-orders processed through manual workflows.',
    calculation: '4,120 Total POs × 20% Consolidation Rate = 824 Fewer Transactions (Direct spend: ₹0)',
    assumption: 'Blanket PO rollout and scheduled batch ordering eliminates redundant transactional overhead.',
    executionMechanism: 'Procurement Process Redesign & Blanket Order System Automation',
    overlapGroup: 'Non-Overlapping (Process Only)',
    exclusionStatus: 'Included (No Monetary Direct Overlap)',
    owner: 'Procurement Operations Head',
    timeline: '60–90 Days',
    status: 'In Design',
    background: 'High PO velocity (4,120 POs annually) creating heavy administrative friction and invoice overhead.',
    objective: 'Reduce transactional noise through blanket ordering, batch releases, and catalog buying.',
    finding: '824 POs can be systematically consolidated through blanket order agreements and batching.',
    valueOpportunity: '20% process effort reduction; direct spend saving ₹0.00 Cr until manpower cost is validated.',
    executionApproach: 'Deploy ERP blanket purchase agreements with automated electronic releases.',
    nextStep: 'Deploy blanket order contracts → enforce monthly batch releases → measure administrative hour savings.',
    validationRequired: 'Internal customer operational time-motion study to monetize processing hours saved.',
    classificationLabel: 'ANALYTICAL FINDING',
    transactionSampleId: 'PO-2025-09142'
  },
  {
    opportunityId: 'OPP-003',
    module: 'Module 3',
    analysis: 'Benchmark Price Gap',
    category: 'Direct Materials & Packaging',
    item: 'Corrugated Boxes & HDPE Liners',
    supplier: 'Incumbent Packaging Suppliers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹1,284.50 Cr',
    valueType: 'DIRECT_PROCUREMENT_SAVING',
    valueTypeLabel: 'Direct Procurement Opportunity',
    lowPercent: '4.50%',
    basePercent: '6.28%',
    highPercent: '8.00%',
    lowValue: '₹57.80 Cr',
    baseValue: '₹80.57 Cr',
    highValue: '₹102.76 Cr',
    indicativeOpportunity: '₹57.80 – ₹102.76 Cr (Base: ₹80.57 Cr)',
    confidence: 'High (Verified Commodity Index Benchmark)',
    dataEvidence: 'Q3 commodity index showed 9.2% market decline while customer contracted rates remained flat.',
    calculation: 'Eligible Spend ₹1,284.50 Cr × Benchmark Gap 6.28% = ₹80.57 Cr Indicative Opportunity',
    assumption: 'Direct material contracts reset to market index benchmark via scheduled quarterly clause.',
    executionMechanism: 'Index-Linked Contract Reset & Commercial Price Alignment',
    overlapGroup: 'GRP-B (Strategic Sourcing & Market Benchmark)',
    exclusionStatus: 'Deducted in Overlap (-₹40.20 Cr net applied)',
    owner: 'Direct Materials Director',
    timeline: '30–60 Days',
    status: 'Active Negotiation',
    background: 'Material contract prices remained static during recent commodity benchmark index declines.',
    objective: 'Align contract pricing with published domestic and international feedstock price indices.',
    finding: 'Eligible material spend of ₹1,284.50 Cr shows a 6.28% unfavorable variance against market indices.',
    valueOpportunity: 'Low: ₹57.80 Cr (4.5%), Base: ₹80.57 Cr (6.28%), High: ₹102.76 Cr (8.0%) price alignment.',
    executionApproach: 'Present index evidence dossier to incumbents; activate contractual index adjustment clause.',
    nextStep: 'Present benchmark evidence dossier → initiate contract price reset discussions → recalibrate pricing.',
    validationRequired: 'Signed contract addendum reflecting revised index-linked price formula.',
    classificationLabel: 'BENCHMARK FINDING',
    transactionSampleId: 'TX-PKG-33104'
  },
  {
    opportunityId: 'OPP-004',
    module: 'Module 2',
    analysis: 'Strategic Sourcing & Competitive Tendering',
    category: 'Logistics, Freight & Facility Services',
    item: 'Full Truckload Freight & Regional Hub Warehousing',
    supplier: '34 Regional Transporters & 3PLs',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹840.00 Cr',
    valueType: 'STRATEGIC_OPPORTUNITY',
    valueTypeLabel: 'Strategic Sourcing Opportunity',
    lowPercent: '6.00%',
    basePercent: '8.50%',
    highPercent: '11.00%',
    lowValue: '₹50.40 Cr',
    baseValue: '₹71.40 Cr',
    highValue: '₹92.40 Cr',
    indicativeOpportunity: '₹50.40 – ₹92.40 Cr (Base: ₹71.40 Cr)',
    confidence: 'Medium-High (Lane Volume Density Model)',
    dataEvidence: '34 carriers operating across 112 lanes with 31% rate divergence on comparable ton-km routes.',
    calculation: 'Eligible Spend ₹840.00 Cr × Sourcing Compression (8.50%) = ₹71.40 Cr Gross Opportunity',
    assumption: 'Corridor bundling, should-cost baseline, and multi-round competitive bidding compress rates.',
    executionMechanism: 'Lane Bundling, Should-Cost Modelling & Targeted Multi-Round Sourcing',
    overlapGroup: 'GRP-B (Strategic Sourcing & Market Benchmark)',
    exclusionStatus: 'Deducted in Overlap (-₹22.60 Cr net applied)',
    owner: 'Logistics Sourcing Lead',
    timeline: '60–120 Days',
    status: 'RFP Formulated',
    background: 'Fragmented lane contracts across 34 logistics service providers with uneven rate structures.',
    objective: 'Optimize logistics network via volume pooling, round-trip commitments, and rate standardisation.',
    finding: '₹840.00 Cr in logistics spend is eligible for network bundling, rate card standardisation, and bidding.',
    valueOpportunity: 'Low: ₹50.40 Cr (6%), Base: ₹71.40 Cr (8.5%), High: ₹92.40 Cr (11%) competitive compression.',
    executionApproach: 'Issue corridor RFP with should-cost price ceilings and automated reverse auction on standard lanes.',
    nextStep: 'Standardize lane specifications → conduct multi-round competitive RFQ → award strategic lane bundles.',
    validationRequired: 'Bilateral master freight agreements and TMS rate card synchronization.',
    classificationLabel: 'PLANNING ASSUMPTION',
    transactionSampleId: 'TX-LOG-44912'
  },
  {
    opportunityId: 'OPP-005',
    module: 'Module 2',
    analysis: 'Supplier Risk Mitigation',
    category: 'Critical APIs & Specialized Chemicals',
    item: 'Monopolistic Reagents & Active Ingredients',
    supplier: '4 Sole-Source Specialized Manufacturers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹420.00 Cr at Risk',
    valueType: 'RISK_COST_AVOIDANCE',
    valueTypeLabel: 'Risk / Cost Avoidance',
    lowPercent: 'Non-Monetized',
    basePercent: 'Non-Monetized',
    highPercent: 'Non-Monetized',
    lowValue: '2 Suppliers',
    baseValue: '4 Suppliers',
    highValue: '4 Suppliers',
    indicativeOpportunity: '4 Dual-Source Programs Qualified (Direct Spend: ₹0.00 Cr / Cost Avoidance)',
    confidence: 'High (Quality & Supply Continuity Audit)',
    dataEvidence: '4 manufacturing plants single-threaded to sole suppliers with zero contracted emergency reserves.',
    calculation: '4 Programs Qualified for Secondary Supply (Direct procurement saving: ₹0.00 Cr)',
    assumption: 'Secondary qualification prevents production halt during supply chain force majeure.',
    executionMechanism: 'Dual-Sourcing Qualification & Strategic Buffer Stock Agreements',
    overlapGroup: 'Non-Overlapping (Risk Protection)',
    exclusionStatus: 'Included (Zero Monetary Overlap)',
    owner: 'Chief Risk Officer / VP Quality',
    timeline: '120–180 Days',
    status: 'In Qualification',
    background: 'Over-concentration in 4 sole-source suppliers posing catastrophic plant shutdown vulnerability.',
    objective: 'Eliminate single-point-of-failure vulnerabilities through rigorous secondary supplier qualification.',
    finding: '₹420.00 Cr of spend exposed to single suppliers without contracted secondary backup capacity.',
    valueOpportunity: 'Supply continuity insurance; direct procurement saving is ₹0.00 Cr unless disruption occurs.',
    executionApproach: 'Conduct plant technical audits for 2 alternative suppliers and execute split-volume SLA.',
    nextStep: 'Audit secondary suppliers → initiate qualification batches → negotiate standby volume SLAs.',
    validationRequired: 'QA regulatory site approval and formal 80/20 volume split contract signing.',
    classificationLabel: 'ANALYTICAL FINDING',
    transactionSampleId: 'TX-CHM-11029'
  },
  {
    opportunityId: 'OPP-006',
    module: 'Module 3',
    analysis: 'Market Trend & Timing Optimization',
    category: 'Packaging Polymers & Energy Contracts',
    item: 'Polypropylene Resin & Grid Power PPA',
    supplier: 'Petrochemical & Independent Power Producers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹310.00 Cr',
    valueType: 'STRATEGIC_OPPORTUNITY',
    valueTypeLabel: 'Market Timing Opportunity',
    lowPercent: '3.00%',
    basePercent: '4.80%',
    highPercent: '6.50%',
    lowValue: '₹9.30 Cr',
    baseValue: '₹14.88 Cr',
    highValue: '₹20.15 Cr',
    indicativeOpportunity: '₹9.30 – ₹20.15 Cr (Base: ₹14.88 Cr)',
    confidence: 'Medium (Commodity Pricing Cycle Projection)',
    dataEvidence: 'Polymer feedstock entering cyclical bottom decile; current forward curves show 4.8% window.',
    calculation: 'Eligible Spend ₹310.00 Cr × Timing Advantage 4.80% = ₹14.88 Cr Gross Timing Benefit',
    assumption: 'Locking 12-month forward contracts during projected low-cycle pricing window shields budget.',
    executionMechanism: 'Fixed-Band Forward Contracts & Scheduled Tender Reset',
    overlapGroup: 'GRP-B (Strategic Sourcing & Market Benchmark)',
    exclusionStatus: 'Subject to Joint Commercial Committee Review',
    owner: 'Treasury & Energy Sourcing Lead',
    timeline: '30 Days',
    status: 'Committee Review',
    background: 'Polymer feedstock pricing entering historical 2-year low cycle window.',
    objective: 'Capture forward market dips through disciplined index hedges and term resets.',
    finding: '₹310.00 Cr spend exposed to spot fluctuations can be stabilized through structured term resets.',
    valueOpportunity: 'Low: ₹9.30 Cr (3%), Base: ₹14.88 Cr (4.8%), High: ₹20.15 Cr (6.5%) strategic timing gain.',
    executionApproach: 'Convene treasury and procurement joint committee to approve forward contract collars.',
    nextStep: 'Convene joint treasury committee → confirm index floor/ceiling → execute fixed-band term contracts.',
    validationRequired: 'Board treasury authorization and counterparty forward contract execution.',
    classificationLabel: 'ESTIMATED OPPORTUNITY',
    transactionSampleId: 'TX-ENG-66712'
  },
  {
    opportunityId: 'OPP-007',
    module: 'Module 4',
    analysis: 'Consolidated Realized Savings',
    category: 'Corporate Services & IT Hardware',
    item: 'Laptops, Cloud Licenses & Enterprise AMC',
    supplier: 'OEM Direct & Enterprise Resellers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹143.00 Cr Approved',
    valueType: 'VALIDATED_SAVING',
    valueTypeLabel: 'Validated & Realized Saving',
    lowPercent: '100% Realized',
    basePercent: '100% Realized',
    highPercent: '100% Realized',
    lowValue: '₹68.00 Cr',
    baseValue: '₹68.00 Cr',
    highValue: '₹68.00 Cr',
    indicativeOpportunity: '₹68.00 Cr Realized (₹143.00 Cr In-Flight Run-Rate)',
    confidence: 'Verified (General Ledger Audited Actuals)',
    dataEvidence: 'Matched invoices against negotiated rate cards verified in SAP ERP ledger for Q1-Q3.',
    calculation: 'Audited Invoice Difference vs Prior Year Baseline = ₹68.00 Cr Net Realized Cash',
    assumption: '100% audited variance realized through strict PO price matching and supplier credit notes.',
    executionMechanism: 'Automated 3-Way Invoice Compliance & Rate Card Enforcement',
    overlapGroup: 'Exempt (Audited Actuals)',
    exclusionStatus: 'Included (Zero Overlap with Unaudited Pipeline)',
    owner: 'CFO Office / Procurement Controller',
    timeline: 'Ongoing Monitoring',
    status: 'Realized & Audited',
    background: 'Previously completed negotiations and signed contracts undergoing invoice audit verification.',
    objective: 'Track dollar-for-dollar financial realization of negotiated procurement concessions.',
    finding: '₹68.00 Cr cash savings audited in general ledger with ₹143.00 Cr total approved program value.',
    valueOpportunity: '₹68.00 Cr bankable cash savings confirmed by finance committee.',
    executionApproach: 'Enforce continuous automated rate-card compliance checking on all incoming PO invoices.',
    nextStep: 'Enforce purchase order rate compliance → flag price variances in automated invoice matching.',
    validationRequired: 'Quarterly internal audit certification and CFO ledger sign-off.',
    classificationLabel: 'VALIDATED SAVING',
    transactionSampleId: 'INV-2025-00481'
  }
];
