/**
 * Executive Brief Master Opportunities - Part 2 (OPP-005 to OPP-007)
 * Conforming strictly to Section 12, Section 15, and Section 18 of Prompt 275.
 */

import type { ExecutiveBriefMasterOpportunityItem } from '../types';
import { EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE } from './executiveBriefGovernance';

export const EXECUTIVE_BRIEF_MASTER_OPPORTUNITIES_PART2: readonly ExecutiveBriefMasterOpportunityItem[] = [
  {
    opportunityId: 'OPP-005',
    module: 'Module 2',
    analysis: 'Supplier Risk Mitigation',
    category: 'Critical APIs & Specialized Chemicals',
    item: 'Monopolistic Reagents & Active Ingredients',
    supplier: '4 Sole-Source Specialized Manufacturers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹420.00 Cr at Risk',
    valueType: 'RISK_COST_AVOIDANCE',
    valueClassification: 'COST_AVOIDANCE',
    valueTypeLabel: 'Risk / Cost Avoidance',
    lowPercent: 'Non-Monetized',
    basePercent: 'Non-Monetized',
    highPercent: 'Non-Monetized',
    lowValue: '2 Suppliers',
    baseValue: '4 Suppliers',
    highValue: '4 Suppliers',
    indicativeOpportunity: '4 Dual-Source Programs Qualified (Direct Spend: ₹0.00 Cr / Cost Avoidance)',
    confidence: 'High (Quality & Supply Continuity Audit)',
    dataEvidence: '4 manufacturing plants single-threaded to sole suppliers with zero contracted emergency reserves.',
    currentState: '4 manufacturing plants single-threaded to sole suppliers with zero contracted emergency reserves.',
    whatWeFound: '₹420.00 Cr spend exposed to 4 sole-source vendors without secondary qualified production sources.',
    whyItMatters: 'Any operational shutdown or force majeure at sole supplier halts entire customer product lines.',
    calculation: '4 Programs Qualified for Secondary Supply (Direct procurement saving: ₹0.00 Cr)',
    calculationMethod: '4 Programs Qualified for Secondary Supply (Direct procurement saving: ₹0.00 Cr / Cost Avoidance)',
    lowCase: '2 Suppliers',
    baseCase: '4 Suppliers',
    highCase: '4 Suppliers',
    assumption: 'Secondary qualification prevents production halt during supply chain force majeure.',
    executionMechanism: 'Dual-Sourcing Qualification & Strategic Buffer Stock Agreements',
    expectedOutcome: 'De-risked supply chain with secondary qualified sources active across all 4 critical programs.',
    overlapGroup: 'Non-Overlapping (Risk Protection)',
    exclusionStatus: 'Included (Zero Monetary Overlap)',
    owner: 'Chief Risk Officer / VP Quality',
    timeline: '120–180 Days',
    status: 'In Qualification',
    background: 'Over-concentration in 4 sole-source suppliers posing catastrophic plant shutdown vulnerability.',
    objective: 'Eliminate single-point-of-failure vulnerabilities through rigorous secondary supplier qualification.',
    finding: '₹420.00 Cr of spend exposed to single suppliers without contracted secondary backup capacity.',
    valueOpportunity: 'Supply continuity insurance; direct procurement saving is ₹0.00 Cr unless disruption occurs.',
    executionApproach: 'Conduct plant technical audits for 2 alternative suppliers and execute split-volume SLA.',
    nextStep: 'Audit secondary suppliers → initiate qualification batches → negotiate standby volume SLAs.',
    validationRequired: 'QA regulatory site approval and formal 80/20 volume split contract signing.',
    customerValidationRequired: 'QA regulatory site approval and formal 80/20 volume split contract signing.',
    classificationLabel: 'ANALYTICAL FINDING',
    transactionSampleId: 'TX-CHM-11029',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-005']
  },
  {
    opportunityId: 'OPP-006',
    module: 'Module 3',
    analysis: 'Market Trend & Timing Optimization',
    category: 'Packaging Polymers & Energy Contracts',
    item: 'Polypropylene Resin & Grid Power PPA',
    supplier: 'Petrochemical & Independent Power Producers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹310.00 Cr',
    valueType: 'STRATEGIC_OPPORTUNITY',
    valueClassification: 'STRATEGIC_VALUE',
    valueTypeLabel: 'Market Timing Opportunity',
    lowPercent: '3.00%',
    basePercent: '4.80%',
    highPercent: '6.50%',
    lowValue: '₹9.30 Cr',
    baseValue: '₹14.88 Cr',
    highValue: '₹20.15 Cr',
    indicativeOpportunity: '₹9.30 – ₹20.15 Cr (Base: ₹14.88 Cr)',
    confidence: 'Medium (Commodity Pricing Cycle Projection)',
    dataEvidence: 'Polymer feedstock entering cyclical bottom decile; current forward curves show 4.8% window.',
    currentState: 'Feedstock spot pricing entering a projected 2-year cyclical low band across benchmark exchanges.',
    whatWeFound: 'Feedstock spot pricing entering a projected 2-year cyclical low band across benchmark exchanges.',
    whyItMatters: 'Entering 12-month forward contracts locks low input costs before anticipated cyclical rebound.',
    calculation: 'Eligible Spend ₹310.00 Cr × Timing Advantage 4.80% = ₹14.88 Cr Gross Timing Benefit',
    calculationMethod: 'Eligible Spend ₹310.00 Cr × Timing Advantage 4.80% = ₹14.88 Cr Gross Timing Benefit',
    lowCase: '₹9.30 Cr (3.0%)',
    baseCase: '₹14.88 Cr (4.8%)',
    highCase: '₹20.15 Cr (6.5%)',
    assumption: 'Locking 12-month forward contracts during projected low-cycle pricing window shields budget.',
    executionMechanism: 'Fixed-Band Forward Contracts & Scheduled Tender Reset',
    expectedOutcome: 'Stabilized input procurement pricing locked below long-term historic cost averages.',
    overlapGroup: 'GRP-B (Strategic Sourcing & Market Benchmark)',
    exclusionStatus: 'Subject to Joint Commercial Committee Review',
    owner: 'Treasury & Energy Sourcing Lead',
    timeline: '30 Days',
    status: 'Committee Review',
    background: 'Polymer feedstock pricing entering historical 2-year low cycle window.',
    objective: 'Capture forward market dips through disciplined index hedges and term resets.',
    finding: '₹310.00 Cr spend exposed to spot fluctuations can be stabilized through structured term resets.',
    valueOpportunity: 'Low: ₹9.30 Cr (3%), Base: ₹14.88 Cr (4.8%), High: ₹20.15 Cr (6.5%) strategic timing gain.',
    executionApproach: 'Convene treasury and procurement joint committee to approve forward contract collars.',
    nextStep: 'Convene joint treasury committee → confirm index floor/ceiling → execute fixed-band term contracts.',
    validationRequired: 'Board treasury authorization and counterparty forward contract execution.',
    customerValidationRequired: 'Board treasury authorization and counterparty forward contract execution.',
    classificationLabel: 'ESTIMATED OPPORTUNITY',
    transactionSampleId: 'TX-ENG-66712',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-006']
  },
  {
    opportunityId: 'OPP-007',
    module: 'Module 4',
    analysis: 'Consolidated Realized Savings',
    category: 'Corporate Services & IT Hardware',
    item: 'Laptops, Cloud Licenses & Enterprise AMC',
    supplier: 'OEM Direct & Enterprise Resellers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹143.00 Cr Approved',
    valueType: 'VALIDATED_SAVING',
    valueClassification: 'REALIZED_SAVING',
    valueTypeLabel: 'Validated & Realized Saving',
    lowPercent: '100% Realized',
    basePercent: '100% Realized',
    highPercent: '100% Realized',
    lowValue: '₹68.00 Cr',
    baseValue: '₹68.00 Cr',
    highValue: '₹68.00 Cr',
    indicativeOpportunity: '₹68.00 Cr Realized (₹143.00 Cr In-Flight Run-Rate)',
    confidence: 'Verified (General Ledger Audited Actuals)',
    dataEvidence: 'Matched invoices against negotiated rate cards verified in SAP ERP ledger for Q1-Q3.',
    currentState: 'Executed commercial agreements validated through invoice audit against baseline historical rates.',
    whatWeFound: 'Executed commercial agreements validated through invoice audit against baseline historical rates.',
    whyItMatters: 'Demonstrates tangible P&L impact already delivered into audited company financial accounts.',
    calculation: 'Audited Invoice Difference vs Prior Year Baseline = ₹68.00 Cr Net Realized Cash',
    calculationMethod: 'Audited Invoice Difference vs Prior Year Baseline = ₹68.00 Cr Net Realized Cash',
    lowCase: '₹68.00 Cr',
    baseCase: '₹68.00 Cr',
    highCase: '₹68.00 Cr',
    assumption: '100% audited variance realized through strict PO price matching and supplier credit notes.',
    executionMechanism: 'Automated 3-Way Invoice Compliance & Rate Card Enforcement',
    expectedOutcome: 'Confirmed cash savings recognized in operational EBITDA and audited financial statements.',
    overlapGroup: 'Exempt (Audited Actuals)',
    exclusionStatus: 'Included (Zero Overlap with Unaudited Pipeline)',
    owner: 'CFO Office / Procurement Controller',
    timeline: 'Ongoing Monitoring',
    status: 'Realized & Audited',
    background: 'Previously completed negotiations and signed contracts undergoing invoice audit verification.',
    objective: 'Track dollar-for-dollar financial realization of negotiated procurement concessions.',
    finding: '₹68.00 Cr cash savings audited in general ledger with ₹143.00 Cr total approved program value.',
    valueOpportunity: '₹68.00 Cr bankable cash savings confirmed by finance committee.',
    executionApproach: 'Enforce continuous automated rate-card compliance checking on all incoming PO invoices.',
    nextStep: 'Enforce purchase order rate compliance → flag price variances in automated invoice matching.',
    validationRequired: 'Quarterly internal audit certification and CFO ledger sign-off.',
    customerValidationRequired: 'Quarterly internal audit certification and CFO ledger sign-off.',
    classificationLabel: 'VALIDATED SAVING',
    transactionSampleId: 'INV-2025-00481',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-007']
  }
];
