/**
 * Executive Brief Master Opportunities - Part 1 (OPP-001 to OPP-004)
 * Conforming strictly to Section 12, Section 15, and Section 18 of Prompt 275.
 */

import type { ExecutiveBriefMasterOpportunityItem } from '../types';
import { EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE } from './executiveBriefGovernance';

export const EXECUTIVE_BRIEF_MASTER_OPPORTUNITIES_PART1: readonly ExecutiveBriefMasterOpportunityItem[] = [
  {
    opportunityId: 'OPP-001',
    module: 'Module 2',
    analysis: 'Vendor Consolidation',
    category: 'Industrial Supplies & MRO',
    item: 'Fasteners, Bearings & Plant Spares',
    supplier: '912 Tail & Regional Vendors',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹154.20 Cr',
    valueType: 'DIRECT_PROCUREMENT_SAVING',
    valueClassification: 'DIRECT_SAVING',
    valueTypeLabel: 'Direct Procurement Opportunity',
    lowPercent: '3.0%',
    basePercent: '4.0%',
    highPercent: '5.0%',
    lowValue: '₹4.63 Cr',
    baseValue: '₹6.17 Cr',
    highValue: '₹7.71 Cr',
    indicativeOpportunity: '₹4.63 – ₹7.71 Cr (Base: ₹6.17 Cr)',
    confidence: 'High (Verified Transaction Dispersion)',
    dataEvidence: '12,480 line items across 912 vendors showing 28% price variance on identical SKUs.',
    currentState: 'Extreme vendor fragmentation with 912 vendors supplying identical plant maintenance parts with 28% price variance.',
    whatWeFound: 'Extreme vendor fragmentation with 912 vendors supplying identical plant maintenance parts.',
    whyItMatters: 'Small, uncoordinated spot buys forfeit tier-1 purchasing power and incur high invoice overhead.',
    calculation: 'Eligible Spend ₹154.20 Cr × Planning Leverage (3%–5%) = ₹4.63–₹7.71 Cr',
    calculationMethod: 'Eligible Spend ₹154.20 Cr × Volume Leverage (3%–5%)',
    lowCase: '₹4.63 Cr (3.0%)',
    baseCase: '₹6.17 Cr (4.0%)',
    highCase: '₹7.71 Cr (5.0%)',
    assumption: 'Volume bundling across 4 preferred regional partners yields 4% baseline price concession.',
    executionMechanism: 'Consolidated RFQ & Bilateral Negotiation (E-auction qualifying for standard fasteners)',
    expectedOutcome: '4 preferred supplier master service agreements with unified rate books and quarterly rebates.',
    overlapGroup: 'GRP-A (Tail & Vendor Consolidation)',
    exclusionStatus: 'Included (Zero Overlap in GRP-A)',
    owner: 'Procurement Category Lead',
    timeline: '90 Days (Phase 1)',
    status: 'Ready for RFP',
    background: 'Supplier fragmentation identified across 912 micro-vendors supplying plant MRO.',
    objective: 'Aggregate fragmented volumes to capture tier-1 volume discounts and contract rate parity.',
    finding: '912 tail vendors represent ₹154.20 Cr of eligible addressable spend with high price dispersion.',
    valueOpportunity: 'Low: ₹4.63 Cr (3%), Base: ₹6.17 Cr (4%), High: ₹7.71 Cr (5%) indicative volume leverage.',
    executionApproach: 'Issue unified RFP to top 4 distributors with master price book and quarterly rebates.',
    nextStep: 'Segment suppliers → issue consolidated RFQ → negotiate volume tiers → award preferred contracts.',
    validationRequired: 'Signed distributor contract rate cards and ERP catalog enablement.',
    customerValidationRequired: 'Signed distributor contract rate cards and ERP catalog enablement.',
    classificationLabel: 'PLANNING ASSUMPTION',
    transactionSampleId: 'TX-MRO-88219',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-001']
  },
  {
    opportunityId: 'OPP-002',
    module: 'Module 2',
    analysis: 'PO Consolidation / Process Productivity',
    category: 'All Addressable Categories',
    item: 'Purchase Orders < ₹2.5 Lakhs',
    supplier: 'Cross-Supplier Transaction Flow',
    customerSpendBase: '₹4,931.00 Cr (4,120 POs)',
    eligibleSpend: '3,296 Target POs',
    valueType: 'PROCESS_PRODUCTIVITY_BENEFIT',
    valueClassification: 'PROCESS_PRODUCTIVITY',
    valueTypeLabel: 'Process Productivity Benefit',
    lowPercent: '15.0%',
    basePercent: '20.0%',
    highPercent: '25.0%',
    lowValue: '618 POs',
    baseValue: '824 POs',
    highValue: '1,030 POs',
    indicativeOpportunity: '20% PO Volume Reduction (824 POs saved, Direct Spend: ₹0.00 Cr)',
    confidence: 'High (ERP PO Velocity Audit)',
    dataEvidence: '4,120 annual POs generated with 42% micro-orders processed through manual workflows.',
    currentState: '4,120 purchase orders issued annually; 42% are low-value spot transactions under ₹2.5 Lakhs.',
    whatWeFound: '4,120 purchase orders issued annually; 42% are low-value spot transactions under ₹2.5 Lakhs.',
    whyItMatters: 'High transactional friction creates heavy buyer workload and administrative invoice processing delays.',
    calculation: '4,120 Total POs × 20% Consolidation Rate = 824 Fewer Transactions (Direct spend: ₹0)',
    calculationMethod: '4,120 Total POs × 20% Consolidation Rate = 824 Fewer Transactions (Direct spend: ₹0 / NOT MONETIZED)',
    lowCase: '618 POs (15.0%)',
    baseCase: '824 POs (20.0%)',
    highCase: '1,030 POs (25.0%)',
    assumption: 'Blanket PO rollout and scheduled batch ordering eliminates redundant transactional overhead.',
    executionMechanism: 'Procurement Process Redesign & Blanket Order System Automation',
    expectedOutcome: '824 fewer POs processed annually, freeing estimated 20% operational buying capacity.',
    overlapGroup: 'Non-Overlapping (Process Only)',
    exclusionStatus: 'Included (No Monetary Direct Overlap)',
    owner: 'Procurement Operations Head',
    timeline: '60–90 Days',
    status: 'In Design',
    background: 'High PO velocity (4,120 POs annually) creating heavy administrative friction and invoice overhead.',
    objective: 'Reduce transactional noise through blanket ordering, batch releases, and catalog buying.',
    finding: '824 POs can be systematically consolidated through blanket order agreements and batching.',
    valueOpportunity: '20% process effort reduction; direct spend saving ₹0.00 Cr until manpower cost is validated.',
    executionApproach: 'Deploy ERP blanket purchase agreements with automated electronic releases.',
    nextStep: 'Deploy blanket order contracts → enforce monthly batch releases → measure administrative hour savings.',
    validationRequired: 'Internal customer operational time-motion study to monetize processing hours saved.',
    customerValidationRequired: 'Internal customer operational time-motion study to monetize processing hours saved.',
    classificationLabel: 'ANALYTICAL FINDING',
    transactionSampleId: 'PO-2025-09142',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-002']
  },
  {
    opportunityId: 'OPP-003',
    module: 'Module 3',
    analysis: 'Benchmark Price Gap',
    category: 'Direct Materials & Packaging',
    item: 'Corrugated Boxes & HDPE Liners',
    supplier: 'Incumbent Packaging Suppliers',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹1,284.50 Cr',
    valueType: 'DIRECT_PROCUREMENT_SAVING',
    valueClassification: 'DIRECT_SAVING',
    valueTypeLabel: 'Direct Procurement Opportunity',
    lowPercent: '4.50%',
    basePercent: '6.28%',
    highPercent: '8.00%',
    lowValue: '₹57.80 Cr',
    baseValue: '₹80.67 Cr',
    highValue: '₹102.76 Cr',
    indicativeOpportunity: '₹57.80 – ₹102.76 Cr (Base: ₹80.67 Cr)',
    confidence: 'High (Verified Commodity Index Benchmark)',
    dataEvidence: 'Q3 commodity index showed 9.2% market decline while customer contracted rates remained flat.',
    currentState: 'Contract prices remained fixed at peak levels despite market-wide paper and polymer feedstock drops.',
    whatWeFound: 'Contract prices remained fixed at peak levels despite market-wide paper and polymer feedstock drops.',
    whyItMatters: 'Unadjusted fixed pricing causes significant margin erosion against market benchmark averages.',
    calculation: 'Eligible Spend ₹1,284.50 Cr × Benchmark Gap 6.28% = ₹80.67 Cr Indicative Opportunity',
    calculationMethod: 'Eligible Spend ₹1,284.50 Cr × Benchmark Gap 6.28% = ₹80.67 Cr Indicative Opportunity',
    lowCase: '₹57.80 Cr (4.5%)',
    baseCase: '₹80.67 Cr (6.28%)',
    highCase: '₹102.76 Cr (8.0%)',
    assumption: 'Direct material contracts reset to market index benchmark via scheduled quarterly clause.',
    executionMechanism: 'Index-Linked Contract Reset & Commercial Price Alignment',
    expectedOutcome: 'Direct contract price reduction aligning purchase rates with Q3 index baseline formula.',
    overlapGroup: 'GRP-B (Strategic Sourcing & Market Benchmark)',
    exclusionStatus: 'Deducted in Overlap (-₹40.20 Cr net applied)',
    owner: 'Direct Materials Director',
    timeline: '30–60 Days',
    status: 'Active Negotiation',
    background: 'Material contract prices remained static during recent commodity benchmark index declines.',
    objective: 'Align contract pricing with published domestic and international feedstock price indices.',
    finding: 'Eligible material spend of ₹1,284.50 Cr shows a 6.28% unfavorable variance against market indices.',
    valueOpportunity: 'Low: ₹57.80 Cr (4.5%), Base: ₹80.67 Cr (6.28%), High: ₹102.76 Cr (8.0%) price alignment.',
    executionApproach: 'Present index evidence dossier to incumbents; activate contractual index adjustment clause.',
    nextStep: 'Present benchmark evidence dossier → initiate contract price reset discussions → recalibrate pricing.',
    validationRequired: 'Signed contract addendum reflecting revised index-linked price formula.',
    customerValidationRequired: 'Signed contract addendum reflecting revised index-linked price formula.',
    classificationLabel: 'BENCHMARK FINDING',
    transactionSampleId: 'TX-PKG-33104',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-003']
  },
  {
    opportunityId: 'OPP-004',
    module: 'Module 2',
    analysis: 'Strategic Sourcing & Competitive Tendering',
    category: 'Logistics, Freight & Facility Services',
    item: 'Full Truckload Freight & Regional Hub Warehousing',
    supplier: '34 Regional Transporters & 3PLs',
    customerSpendBase: '₹4,931.00 Cr',
    eligibleSpend: '₹840.00 Cr',
    valueType: 'STRATEGIC_OPPORTUNITY',
    valueClassification: 'DIRECT_SAVING',
    valueTypeLabel: 'Strategic Sourcing Opportunity',
    lowPercent: '6.00%',
    basePercent: '8.50%',
    highPercent: '11.00%',
    lowValue: '₹50.40 Cr',
    baseValue: '₹71.40 Cr',
    highValue: '₹92.40 Cr',
    indicativeOpportunity: '₹50.40 – ₹92.40 Cr (Base: ₹71.40 Cr)',
    confidence: 'Medium-High (Lane Volume Density Model)',
    dataEvidence: '34 carriers operating across 112 lanes with 31% rate divergence on comparable ton-km routes.',
    currentState: '34 carriers operating across 112 lanes with 31% rate divergence on comparable ton-km routes.',
    whatWeFound: 'Fragmented transporter allocation with significant lane rate disparity across identical corridors.',
    whyItMatters: 'Unbundled single-lane negotiations miss return-haul efficiency and volume scale discounts.',
    calculation: 'Eligible Spend ₹840.00 Cr × Sourcing Compression (8.50%) = ₹71.40 Cr Gross Opportunity',
    calculationMethod: 'Eligible Spend ₹840.00 Cr × Sourcing Compression (8.50%) = ₹71.40 Cr Gross Opportunity',
    lowCase: '₹50.40 Cr (6.0%)',
    baseCase: '₹71.40 Cr (8.5%)',
    highCase: '₹92.40 Cr (11.0%)',
    assumption: 'Corridor bundling, should-cost baseline, and multi-round competitive bidding compress rates.',
    executionMechanism: 'Lane Bundling, Should-Cost Modelling & Targeted Multi-Round Sourcing',
    expectedOutcome: 'Consolidated corridor awards yielding 8.5% rate compression and higher carrier commitment.',
    overlapGroup: 'GRP-B (Strategic Sourcing & Market Benchmark)',
    exclusionStatus: 'Deducted in Overlap (-₹22.60 Cr net applied)',
    owner: 'Logistics Sourcing Lead',
    timeline: '60–120 Days',
    status: 'RFP Formulated',
    background: 'Fragmented lane contracts across 34 logistics service providers with uneven rate structures.',
    objective: 'Optimize logistics network via volume pooling, round-trip commitments, and rate standardisation.',
    finding: '₹840.00 Cr in logistics spend is eligible for network bundling, rate card standardisation, and bidding.',
    valueOpportunity: 'Low: ₹50.40 Cr (6%), Base: ₹71.40 Cr (8.5%), High: ₹92.40 Cr (11%) competitive compression.',
    executionApproach: 'Issue corridor RFP with should-cost price ceilings and automated reverse auction on standard lanes.',
    nextStep: 'Standardize lane specifications → conduct multi-round competitive RFQ → award strategic lane bundles.',
    validationRequired: 'Bilateral master freight agreements and TMS rate card synchronization.',
    customerValidationRequired: 'Bilateral master freight agreements and TMS rate card synchronization.',
    classificationLabel: 'PLANNING ASSUMPTION',
    transactionSampleId: 'TX-LOG-44912',
    transactionProof: EXECUTIVE_BRIEF_TRANSACTION_EVIDENCE['OPP-004']
  }
];
