/**
 * Savings Opportunity Register - Part 2 (Prompt 269)
 * Module 2 (Auctions/Risk/Spec), Module 3 PCBI Benchmarks & Module 4 Overlaps (Items 7 to 13)
 */

import type { SavingsOpportunityRegisterItem } from '../types/savingsOpportunityRegister';
import { SAVINGS_ASSUMPTIONS } from './savingsAssumptions';

export const SAVINGS_OPPORTUNITY_REGISTER_PART2: SavingsOpportunityRegisterItem[] = [
  // 7. Module 2: E-Auction Dynamic Reverse Bidding (ONE Sourcing Lever)
  {
    opportunityId: 'OPP-M2-06',
    module: 'Module 2',
    analysisType: 'E_AUCTION',
    category: 'Packaging Materials',
    subCategory: 'Double Laminated HDPE 50kg Cement Sacks',
    currentSpendInr: 3200000000.0,
    addressableSpendInr: 320000000.0,
    currentBaseline: '14 qualified manufacturers with 16.2% historical price dispersion',
    targetImprovement: 'Standardized English reverse e-auction with reserve price set at historical P10',
    savingsPercent: SAVINGS_ASSUMPTIONS.E_AUCTION_IMPROVEMENT * 100,
    estimatedSavingsInr: 19200000.0,
    savingsType: 'HARD_PROCUREMENT_SAVINGS',
    confidenceLevel: 'HIGH',
    calculationMethod: `Auction-Suitable Spend (₹320 Cr) * Auction Improvement (${(
      SAVINGS_ASSUMPTIONS.E_AUCTION_IMPROVEMENT * 100
    ).toFixed(0)}%)`,
    keyAssumption: 'E-auction applied ONLY to standardized, liquid categories with 5+ qualified bidders',
    finding: 'Packaging materials display strong supplier liquidity and standardized technical specifications',
    background: SAVINGS_ASSUMPTIONS.E_AUCTION_DISCLAIMER,
    objective: 'Rapid, transparent dynamic price discovery among pre-qualified manufacturers',
    recommendedAction: 'Execute multi-lot English dynamic reverse auction via ProCPX engine',
    expectedOutcome: 'L1 price discovery driven by real-time competitive bidding compression',
    nextStep: 'Finalize technical specification sign-off and issue auction rulebook to bidders',
    implementationComplexity: 'LOW',
    priority: 'WAVE_1',
    owner: 'Procucev Sourcing Pod & Corporate Procurement',
    realizationTimeline: '0–30 Days',
    overlapGroup: 'OG-PACKAGING',
    consolidationStatus: 'INCLUDED'
  },

  // 8. Module 2: Single-Supplier / Strategic Risk Mitigation
  {
    opportunityId: 'OPP-M2-07',
    module: 'Module 2',
    analysisType: 'STRATEGIC_RISK',
    category: 'Refractory & Kiln Materials',
    subCategory: 'High Alumina Bricks & Pre-Cast Burner Shapes',
    currentSpendInr: 4500000000.0,
    addressableSpendInr: 450000000.0,
    currentBaseline: '100% dependency on single European OEM with 18-week lead times',
    targetImprovement: 'Develop and qualify 2 domestic alternative suppliers to de-risk kiln shutdowns',
    savingsPercent: 0.0,
    estimatedSavingsInr: 0.0, // Risk mitigation benefit, NOT synthetic savings!
    savingsType: 'RISK_STRATEGIC_BENEFIT',
    confidenceLevel: 'HIGH',
    calculationMethod: 'Supply continuity insurance and risk mitigation; 0 direct savings recognized',
    keyAssumption: SAVINGS_ASSUMPTIONS.STRATEGIC_RISK_DISCLAIMER,
    finding: 'Single supplier dependency creates severe operational shutdown exposure and zero negotiation leverage',
    background: 'Disruptions in kiln refractory supply threaten entire plant clinker production lines',
    objective: 'Establish qualified secondary and tertiary domestic manufacturing sources',
    recommendedAction: 'Initiate vendor development and sample trial testing for domestic alternatives',
    expectedOutcome: 'Mitigated supply chain risk, lead time reduced from 18 to 4 weeks, zero plant downtime',
    nextStep: 'Initiate plant technical validation of domestic refractory trial batches',
    implementationComplexity: 'HIGH',
    priority: 'WAVE_2',
    owner: 'Plant Technical Director & Sourcing Lead',
    realizationTimeline: '60–120 Days',
    overlapGroup: 'OG-STRATEGIC-RISK',
    consolidationStatus: 'INCLUDED'
  },

  // 9. Module 2: Category Specification Standardization
  {
    opportunityId: 'OPP-M2-08',
    module: 'Module 2',
    analysisType: 'SPECIFICATION_STANDARDIZATION',
    category: 'Packaging Materials',
    subCategory: 'HDPE Bag GSM & Micron Standardization',
    currentSpendInr: 5500000000.0,
    addressableSpendInr: 550000000.0,
    currentBaseline: '7 differing bag thickness specifications ordered across manufacturing plants',
    targetImprovement: 'Standardize to 2 optimal high-tensile GSM specifications nationwide',
    savingsPercent: 3.0,
    estimatedSavingsInr: 16500000.0,
    savingsType: 'HARD_PROCUREMENT_SAVINGS',
    confidenceLevel: 'MEDIUM',
    calculationMethod: 'Eligible Spend (₹550 Cr) * Spec Optimization (3.0%)',
    keyAssumption: 'Tensile and drop-test performance maintained with optimized resin blend',
    finding: 'Multiple redundant specifications fragment manufacturing orders and prevent scale',
    background: 'Over-specifying bag thickness creates unnecessary raw material polymer weight cost',
    objective: 'Harmonize technical specifications based on audited drop-test and moisture metrics',
    recommendedAction: 'Adopt unified national packaging specification and update ERP part catalog',
    expectedOutcome: 'Direct material weight reduction saving ₹16.50 Cr without compromising bag integrity',
    nextStep: 'Conduct joint quality assurance field trials at 2 regional packaging lines',
    implementationComplexity: 'MEDIUM',
    priority: 'WAVE_2',
    owner: 'Joint Quality & Sourcing Committee',
    realizationTimeline: '60–90 Days',
    overlapGroup: 'OG-PACKAGING-SPEC',
    consolidationStatus: 'INCLUDED'
  },

  // 10. Module 3: PCBI Benchmark Gap - Imported Petcoke
  {
    opportunityId: 'OPP-M3-01',
    module: 'Module 3',
    analysisType: 'PCBI_BENCHMARK_GAP',
    category: 'Energy & Thermal Fuels',
    subCategory: 'Imported Petroleum Coke (6.5% Max Sulfur)',
    currentSpendInr: 16245000000.0,
    addressableSpendInr: 1624500000.0,
    currentBaseline: 'Contract landed price ₹13,850/MT CIF West Coast Port',
    targetImprovement: 'Align purchase contracts with PCBI Global Landed Index benchmark (₹12,980/MT, -6.28%)',
    savingsPercent: 6.28,
    estimatedSavingsInr: 102000000.0,
    savingsType: 'HARD_PROCUREMENT_SAVINGS',
    confidenceLevel: 'HIGH',
    calculationMethod: 'Eligible Import Volume (1.17M MT) * Price Variance Gap (₹870/MT) = ₹102.00 Cr',
    keyAssumption: 'PCBI Grade A+ verified benchmark based on customs port manifests and index data',
    finding: 'Client pays 6.28% premium over PCBI Grade A+ independent landed port import benchmark',
    background: SAVINGS_ASSUMPTIONS.PCBI_BENCHMARK_DISCLAIMER,
    objective: 'Reset commercial contracts to transparent market index-linked pricing formula',
    recommendedAction: 'Renegotiate term contracts with monthly indexation tied to PCBI petcoke index',
    expectedOutcome: 'Immediate alignment with international landed market pricing and margin expansion',
    nextStep: 'Present audited PCBI benchmark dossier during quarterly supplier contract resets',
    implementationComplexity: 'LOW',
    priority: 'WAVE_1',
    owner: 'Head of Energy Procurement',
    realizationTimeline: '0–30 Days',
    overlapGroup: 'OG-ENERGY-FUELS',
    consolidationStatus: 'INCLUDED'
  },

  // 11. Module 3: PCBI Benchmark Gap - Polypropylene Resin
  {
    opportunityId: 'OPP-M3-02',
    module: 'Module 3',
    analysisType: 'PCBI_BENCHMARK_GAP',
    category: 'Packaging Raw Materials',
    subCategory: 'Polypropylene Homopolymer Raffia Grade',
    currentSpendInr: 4800000000.0,
    addressableSpendInr: 480000000.0,
    currentBaseline: 'Customer historical contracted price ₹98.50/KG ex-refinery',
    targetImprovement: 'Align converter contracts with PCBI Petrochemical Benchmark (₹91.20/KG, -7.41%)',
    savingsPercent: 7.41,
    estimatedSavingsInr: 35500000.0,
    savingsType: 'HARD_PROCUREMENT_SAVINGS',
    confidenceLevel: 'HIGH',
    calculationMethod: 'Eligible Resin Volume (48,700 MT) * Benchmark Gap (₹7.30/KG) = ₹35.50 Cr',
    keyAssumption: 'Converter contracts operate on transparent resin cost passthrough mechanism',
    finding: 'HDPE/PP bag converters bill at static resin rates despite market index drops',
    background: 'Resin constitutes ~65% of bag cost; indexation ensures client captures market declines',
    objective: 'Implement transparent resin pass-through formula tied to monthly published spot prices',
    recommendedAction: 'Amend converter master service agreements to incorporate PCBI resin index',
    expectedOutcome: 'Direct pass-through savings realized every month resin market softens',
    nextStep: 'Issue contract amendment annexures with monthly index calculation formula',
    implementationComplexity: 'LOW',
    priority: 'WAVE_1',
    owner: 'Packaging Category Manager',
    realizationTimeline: '0–30 Days',
    overlapGroup: 'OG-PACKAGING-RESIN',
    consolidationStatus: 'INCLUDED'
  },

  // 12. Module 3: Price Trend & Timing Opportunity - Imported Coal
  {
    opportunityId: 'OPP-M3-03',
    module: 'Module 3',
    analysisType: 'PRICE_TREND_TIMING',
    category: 'Energy & Thermal Fuels',
    subCategory: 'Imported Thermal Coal (GAR 5000 kcal/kg)',
    currentSpendInr: 8640000000.0,
    addressableSpendInr: 864000000.0,
    currentBaseline: 'Long-term fixed price contract while seaborne index is declining',
    targetImprovement: 'Capture market timing corridor and restructure contracts to indexed collar',
    savingsPercent: 4.75,
    estimatedSavingsInr: 41000000.0,
    savingsType: 'COST_AVOIDANCE',
    confidenceLevel: 'HIGH',
    calculationMethod: 'Seaborne coal index trend analysis indicates favorable renegotiation window',
    keyAssumption: 'Timing opportunity: Seaborne spot rates softening ahead of seasonal monsoon inventory build',
    finding: 'Market indices display downward price trend while customer fixed pricing remains elevated',
    background: 'Favorable negotiation timing window prevents price escalation and secures downside capture',
    objective: 'Convert fixed pricing into flexible collar contracts capturing seaborne declines',
    recommendedAction: 'Engage suppliers during current favorable negotiation window to reset base prices',
    expectedOutcome: 'Avoided budget overruns and protected cost baseline against market volatility',
    nextStep: 'Issue request for contract price review referencing PCBI coal index trajectory',
    implementationComplexity: 'MEDIUM',
    priority: 'WAVE_1',
    owner: 'Head of Energy Procurement',
    realizationTimeline: '30–60 Days',
    overlapGroup: 'OG-COAL-TREND',
    consolidationStatus: 'INCLUDED'
  },

  // 13. Module 4: Overlap Deduplication & Cannibalization Control
  {
    opportunityId: 'OPP-M4-01',
    module: 'Module 4',
    analysisType: 'STRATEGIC_SOURCING',
    category: 'Consolidated Governance',
    subCategory: 'Multi-Lever Overlap & Exclusions Filter',
    currentSpendInr: 0.0,
    addressableSpendInr: 1250000000.0,
    currentBaseline: 'Identified overlaps between price harmonization, volume aggregation, and auctions',
    targetImprovement: 'Deduplicate overlapping opportunities to ensure 100% board-defensible savings',
    savingsPercent: 0.0,
    estimatedSavingsInr: -62800000.0, // Overlap adjustment (reduction)
    savingsType: 'HARD_PROCUREMENT_SAVINGS',
    confidenceLevel: 'HIGH',
    calculationMethod:
      'Mutual exclusivity matrix: E-Auction Packaging Overlap (-₹38.40 Cr) + Volume Aggregation Overlap (-₹24.40 Cr)',
    keyAssumption: 'No single rupee of spend may yield savings from multiple mutually exclusive levers',
    finding: 'Packaging and consumable categories were identified across both auction and consolidation levers',
    background: 'Independent lever addition overstates defensible P&L savings without overlap controls',
    objective: 'Eliminate double-counting and produce accounting-compliant savings forecast',
    recommendedAction: 'Apply overlap filter isolating primary opportunity from execution mechanisms',
    expectedOutcome: 'Audited, mathematically verified net defensible savings total approved by CFO',
    nextStep: 'Lock deduplicated figures into Wave 1 Procurement Execution Charter',
    implementationComplexity: 'LOW',
    priority: 'WAVE_1',
    owner: 'Procucev Lead Engagement Partner',
    realizationTimeline: '0–30 Days',
    overlapGroup: 'OG-OVERLAP-FILTER',
    consolidationStatus: 'OVERLAPPING'
  }
];
