/**
 * Subscription, Entitlement & Activation Constants (Frontend Prompt 288)
 */

export const SUBSCRIPTION_TIERS = {
  BRONZE: 'BRONZE',
  SILVER: 'SILVER',
  GOLD: 'GOLD'
} as const;

export const SUBSCRIPTION_STATES = {
  FREE: 'FREE',
  PENDING_ACTIVATION: 'PENDING_ACTIVATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
} as const;

export const COMMERCIAL_STATUS = {
  FREE_TIER: 'FREE_TIER',
  QUOTED: 'QUOTED',
  INVOICED: 'INVOICED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  COMPLETED: 'COMPLETED'
} as const;

export const FEATURE_PERMISSIONS = {
  REGISTRATION: 'REGISTRATION',
  LOGIN: 'LOGIN',
  DATA_UPLOAD: 'DATA_UPLOAD',
  SPEND_SUMMARY: 'SPEND_SUMMARY',
  SPEND_DETAIL: 'SPEND_DETAIL',
  SUPPLIER_SUMMARY: 'SUPPLIER_SUMMARY',
  SUPPLIER_OPPORTUNITY: 'SUPPLIER_OPPORTUNITY',
  ITEM_LEVEL_OPPORTUNITY: 'ITEM_LEVEL_OPPORTUNITY',
  CATEGORY_SUMMARY: 'CATEGORY_SUMMARY',
  CATEGORY_OPPORTUNITY: 'CATEGORY_OPPORTUNITY',
  PLANT_SUMMARY: 'PLANT_SUMMARY',
  PRICE_DISPERSION_SUMMARY: 'PRICE_DISPERSION_SUMMARY',
  PRICE_DISPERSION_FULL: 'PRICE_DISPERSION_FULL',
  SAVINGS_INDICATOR: 'SAVINGS_INDICATOR',
  TOTAL_SAVINGS: 'TOTAL_SAVINGS',
  SAVINGS_BY_CATEGORY_BROAD: 'SAVINGS_BY_CATEGORY_BROAD',
  SAVINGS_BY_CATEGORY_DETAILED: 'SAVINGS_BY_CATEGORY_DETAILED',
  SAVINGS_BY_SUPPLIER: 'SAVINGS_BY_SUPPLIER',
  MODULE_2_SUMMARY: 'MODULE_2_SUMMARY',
  MODULE_2_FULL: 'MODULE_2_FULL',
  MODULE_3_SUMMARY: 'MODULE_3_SUMMARY',
  MODULE_3_FULL: 'MODULE_3_FULL',
  PCBI_SUMMARY: 'PCBI_SUMMARY',
  PCBI_DETAIL: 'PCBI_DETAIL',
  BENCHMARK_SUMMARY: 'BENCHMARK_SUMMARY',
  BENCHMARK_SOURCE_DETAIL: 'BENCHMARK_SOURCE_DETAIL',
  MODULE_4_SUMMARY: 'MODULE_4_SUMMARY',
  MODULE_4_FULL: 'MODULE_4_FULL',
  SAVINGS_WATERFALL_SUMMARY: 'SAVINGS_WATERFALL_SUMMARY',
  SAVINGS_WATERFALL_FULL: 'SAVINGS_WATERFALL_FULL',
  SAVINGS_REALIZATION_SUMMARY: 'SAVINGS_REALIZATION_SUMMARY',
  SAVINGS_REALIZATION_FULL: 'SAVINGS_REALIZATION_FULL',
  ACTION_TRACKER: 'ACTION_TRACKER',
  MANAGEMENT_QUICK_SUMMARY: 'MANAGEMENT_QUICK_SUMMARY',
  BOARDROOM_EVIDENCE_SUMMARY: 'BOARDROOM_EVIDENCE_SUMMARY',
  BOARDROOM_EVIDENCE_FULL: 'BOARDROOM_EVIDENCE_FULL',
  PDF_EXPORT_SUMMARY: 'PDF_EXPORT_SUMMARY',
  PDF_EXPORT_FULL: 'PDF_EXPORT_FULL',
  PPTX_EXPORT_SUMMARY: 'PPTX_EXPORT_SUMMARY',
  PPTX_EXPORT_FULL: 'PPTX_EXPORT_FULL',
  DETAILED_DATA_EXPORT: 'DETAILED_DATA_EXPORT',
  ADMIN_SUBSCRIPTION_MANAGEMENT: 'ADMIN_SUBSCRIPTION_MANAGEMENT'
} as const;

export const TIER_DISPLAY_CONFIG = {
  BRONZE: {
    tier: 'BRONZE' as const,
    name: 'Bronze',
    edition: 'Discover',
    statusLabel: 'Free Plan',
    description: 'Procurement baseline ingestion, category breakdown, supplier distribution & initial opportunity indicators.',
    cta: 'Explore Silver'
  },
  SILVER: {
    tier: 'SILVER' as const,
    name: 'Silver',
    edition: 'Assess',
    statusLabel: 'Active Paid',
    description: 'Executive opportunity brief, total savings quantification, broad category levers & benchmark indices.',
    cta: 'Explore Gold'
  },
  GOLD: {
    tier: 'GOLD' as const,
    name: 'Gold',
    edition: 'Optimize',
    statusLabel: 'Enterprise Full',
    description: 'Complete strategic sourcing deep dives, supplier-level savings ledger, item-level PCBI & full boardroom reports.',
    cta: 'Full Access'
  }
} as const;
