/**
 * Centralized UI Strings & Internationalization (i18n) Constants Module
 * 
 * All user-facing literal strings across components, modals, and views are centralized here.
 * For dynamic strings requiring runtime substitution, parameterized template functions are provided.
 */

export const UI_STRINGS = {
  common: {
    brand: 'PROCUCEV',
    appName: 'PROCUCEV',
    engineVersion: 'ENGINE 2.0',
    loading: 'Loading...',
    save: 'Save Changes',
    cancel: 'Cancel',
    close: 'Close',
    export: 'Export Data',
    exportCSV: 'Export CSV',
    exportPDF: 'Export Executive PDF',
    search: 'Search...',
    filter: 'Filter',
    reset: 'Reset',
    apply: 'Apply',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    proceed: 'Proceed',
    status: 'Status',
    action: 'Action',
    actions: 'Actions',
    active: 'Active',
    completed: 'Completed',
    pending: 'Pending',
    verified: 'Verified',
    unverified: 'Unverified',
    all: 'All',
    error: 'An error occurred',
    retry: 'Retry',
    success: 'Success',
    notAvailable: 'N/A',
    viewDetails: 'View Details',
    selectOption: 'Select an option'
  },

  header: {
    brand: 'PROCUCEV',
    appName: 'PROCUCEV',
    engineVersion: 'ENGINE 2.0',
    docRefLabel: 'DOC REF:',
    docRefValue: 'FRD-PRC-2026-V2',
    docRef: (ref: string) => `DOC REF: ${ref}`,
    authorLabel: 'Author:',
    authorName: 'Srinivas Mukku',
    authorRole: 'Co-Founder & CEO',
    authorFull: 'Author: Srinivas Mukku (Co-Founder & CEO)',
    authorFormatted: (name: string, role: string) => `Author: ${name} (${role})`,
    baseCurrencyNote: 'Base Currency: INR in Crores (₹ Cr) | Multi-Currency Live FX',
    slaText: 'SLA: <800ms Query',
    slaQuery: (ms: number) => `SLA: <${ms}ms Query`,
    enterpriseFallback: 'Enterprise',
    evaluatedSpendFallback: '₹732.41 Cr',
    totalSpendEvaluatedPrefix: 'Total Spend Evaluated: ',
    viewExecutiveReport: 'View Executive Report',
    themeToggleDark: 'Switch to Dark Mode',
    themeToggleLight: 'Switch to Light Mode',
    themeSwitchDark: 'Switch to Dark Mode',
    themeSwitchLight: 'Switch to Light Mode',
    light: 'Light',
    dark: 'Dark',
    executiveBrief: 'Executive Brief',
    reportButton: 'Executive Brief',
    currencies: {
      inr: '₹ INR (Cr)',
      usd: 'USD',
      eur: 'EUR',
      gbp: 'GBP'
    },
    currencyTitle: (code: string) => `${code} Base`,
    inrCurrencyTitle: 'Indian Rupee in Crores (₹ Cr)',
    multiCurrencyLiveFX: 'Multi-Currency Live FX',
    inrCroresSymbol: '₹ Cr',
    subtitle: 'Tech-Enabled Procurement Advisory & Real-Time AI Optimization Suite',
    securityBadge: 'SOC2 Type II / AES-256'
  },

  pipeline: {
    title: 'Consulting Delivery Pipeline (Stages 1 - 5)',
    subtitle: 'End-to-end algorithmic spend evaluation from ERP ingestion to EBITDA savings',
    endToEndArchitecture: 'End-to-End Processing Pipeline & Architecture',
    conversionMatrixTab: '5. Conversion Matrix',
    dataArchitectureTab: 'Data Architecture',
    dataArchitecture: 'Data Architecture',
    currentActiveView: 'Current Active View',
    exploreModule: 'Explore Module',
    currentStagePrefix: 'Current Active Stage: ',
    currentStage: (num: number, title: string) => `Current Active Stage: [Stage ${num}: ${title}]`,
    pipelineComplete: 'Pipeline Complete: All 5 Stages Ready for Client Lock-In',
    lockInReady: 'Ready for Client Sign-Off',
    viewSchemaButton: 'Data Architecture / DDL Schema View',
    steps: {
      step1: {
        title: '3-Year Upload',
        desc: 'Invoices, POs, receipts & multi-format contracts'
      },
      step2: {
        title: 'AI Categorization',
        desc: 'Automated taxonomy & vendor disambiguation'
      },
      step3: {
        title: 'Trend Analysis',
        desc: '36-month material base price & markup tracking'
      },
      step4: {
        title: 'Savings Engine',
        desc: 'Real-time opportunity mapping & UI alerts'
      }
    },
    kpis: {
      historicalIngestion: {
        label: 'Historical Ingestion',
        value: '3 Yrs',
        sub: '36-Month Full Horizon'
      },
      realTimeProcessing: {
        label: 'Real-Time Processing',
        value: '100%',
        sub: 'Sub-800ms Query Render'
      },
      avgIdentifiedSavings: {
        label: 'Avg Identified Savings',
        value: '15%+',
        sub: 'Realized Benchmark'
      },
      fasterConversion: {
        label: 'Faster Conversion',
        value: '3x',
        sub: 'Advisory to SaaS Lock-in'
      }
    },
    navStages: {
      step1: {
        title: '3-Year Upload',
        desc: 'Invoices, POs, receipts & multi-format contracts'
      },
      step2: {
        title: 'AI Categorization',
        desc: 'Automated taxonomy & vendor disambiguation'
      },
      step3: {
        title: 'Trend Analysis',
        desc: '36-month material base price & markup tracking'
      },
      step4: {
        title: 'Savings Engine',
        desc: 'Real-time opportunity mapping & UI alerts'
      }
    },
    stages: {
      1: {
        number: 1,
        title: 'Data Ingestion',
        sublabel: 'Stage 1: Multi-ERP Normalization',
        badge: 'STAGE 1'
      },
      2: {
        number: 2,
        title: 'UNSPSC Taxonomy',
        sublabel: 'Stage 2: 4-Tier AI Categorization',
        badge: 'STAGE 2'
      },
      3: {
        number: 3,
        title: 'Price Volatility',
        sublabel: 'Stage 3: Spend & Leakage Analytics',
        badge: 'STAGE 3'
      },
      4: {
        number: 4,
        title: 'Opportunity Engine',
        sublabel: 'Stage 4: ProCPX & DPS NXT Modules',
        badge: 'STAGE 4'
      },
      5: {
        number: 5,
        title: 'Lock-In Matrix',
        sublabel: 'Stage 5: Client Sign-Off & EBITDA',
        badge: 'STAGE 5'
      }
    }
  },

  schema: {
    title: 'PostgreSQL Enterprise Data Architecture & Prisma DDL Schema',
    subtitle: 'Normalized relational schema with multi-tenant isolation, UUID surrogate keys, and foreign keys.',
    bannerBadge: 'FRD Section 5 & 6',
    bannerSubtitle: 'PostgreSQL / Snowflake Database Schema & NFRs',
    bannerTitle: 'Data Architecture & Security SLA Specifications',
    bannerDescription: 'Core normalized relational database schema powering the high-performance ETL pipeline and real-time analytics engine.',
    securityBadge: 'AES-256 / TLS 1.3 Active',
    entitiesHeader: 'Database Core Entities (6)',
    tableTypeBadge: 'PostgreSQL / Snowflake Table',
    tabs: {
      attributes: 'Attributes',
      sqlDdl: 'SQL DDL',
      sampleData: 'JSON Preview'
    },
    primaryAttributesLabel: 'Primary Attributes / Fields:',
    slaCards: {
      performanceTitle: 'System Performance SLA',
      securityTitle: 'Security & Global Compliance',
      uptimeTitle: 'System Uptime & Failover'
    },
    entityCountBadge: '10 Relational Tables',
    backToPipeline: 'Back to Pipeline',
    activeEntity: 'Active Entity',
    ddlSpecification: 'DDL Specification',
    attributesCount: (n: number) => `${n} Attributes`,
    liveSampleData: 'Live Sample Data (First 3 Records)',
    copyDDL: 'Copy DDL',
    copied: 'Copied!',
    tableDescriptionHeader: 'Table Description & Business Context',
    primaryKey: 'Primary Key',
    nullable: 'Nullable',
    foreignKey: 'Foreign Key',
    noSampleData: 'No sample data available for this entity.'
  },

  module1: {
    title: 'Multi-ERP Ingestion & Normalization Engine',
    subtitle: 'SAP, Oracle & Infor Ingestion Pipeline with Pre-Categorization Remediation',
    badge: 'Module 1: Document Ingestion & Multi-Currency ETL',
    fxEngineActive: 'Multi-Currency FX Engine Active',
    heading: '3-Year Multi-Currency Ingestion & FX Normalization',
    description: 'Ingests multiple foreign currencies (USD, EUR, GBP, AED, JPY, SGD), applies historical time-series FX conversion rates, and normalizes all spend into INR in Crores (₹ Cr).',
    uploadedFileDetails: 'Uploaded Procurement File Details',
    dropzoneTitle: 'Drag & drop ERP spend extracts or purchase histories',
    dropzoneSupported: 'Supported formats: CSV, XLSX, XML, JSON exports from SAP S/4HANA, Oracle ERP, Infor LN, or Microsoft Dynamics 365',
    browseFiles: 'Browse Files',
    byCategories: 'By Categories',
    byVendors: 'By Vendors',
    actions: {
      fixCurrency: 'Fix (INR)',
      mergeVendor: 'Merge Vendor',
      viewDetails: 'Details',
      recalcFx: 'Recalc FX'
    },
    fixInr: 'Fix (INR)',
    recalcFx: 'Recalc FX',
    mergeVendor: 'Merge Vendor',
    applyBlanketFixes: 'Apply Blanket AI Fixes',
    runAiCategorization: 'Run AI Categorization Engine',
    resetAnomalyState: 'Reset Anomaly State',
    noFileUploaded: 'No file uploaded yet',
    configureClientDataset: 'Configure Client & Dataset',
    confirmAndProceedToUpload: 'Confirm & Proceed to Upload Data',
    needsAction: 'Needs Action',
    readyAndCleared: 'Ready & Cleared',
    allRecords: 'All Records',
    viewBalanceCategories: (count: number) => `View ${count} Balance Categories`,
    hideBalanceCategories: (count: number) => `Hide ${count} Balance Categories`,
    viewBalanceSuppliers: (count: number) => `View ${count} Balance Suppliers`,
    hideBalanceSuppliers: (count: number) => `Hide ${count} Balance Suppliers`,
    allFy: 'All FY',
    closePopup: 'Close Pop-up',
    processingStatus: (pct: number) => `${pct}% Processing`,
    ingestionQueueTitle: 'Active ERP Ingestion Queue',
    ingestionQueueSubtitle: 'Real-time extraction and staging status across enterprise entities',
    validationTitle: 'Ingestion Validation & Remediation Log',
    validationSubtitle: 'Pre-categorization anomaly detection, currency normalization & vendor entity de-duplication',
    selectFile: 'Select File to Ingest',
    dragAndDrop: 'Drag and drop your raw ERP export here (CSV, XLSX, XML, PDF)',
    supportedFormats: 'Supported: SAP ECC/S4HANA, Oracle Fusion, Infor M3/LN, Custom CSV',
    setupDetails: 'Setup Details',
    changeDetails: 'Change Details',
    resetValidation: 'Reset to Baseline',
    proceedToCategorization: 'Proceed to Stage 2: UNSPSC Taxonomy & Categorization',
    filterAll: 'All Issues',
    filterCurrency: 'Currency Anomalies',
    filterVendor: 'Vendor Duplicates',
    filterMissing: 'Missing Fields',
    filterValid: 'Clean / Resolved',
    tableHeaders: {
      recordId: 'Record ID',
      erpSource: 'ERP Source',
      vendorIdentified: 'Vendor Identified',
      rawDescription: 'Raw Description',
      amountReported: 'Amount Reported',
      normalizedINR: 'Normalized (INR)',
      issueDetected: 'Issue Detected',
      remediationStatus: 'Status',
      actions: 'Actions'
    },
    breakdown: {
      yearFilterLabel: 'Year View:',
      modeVendor: 'Vendor Spend Breakdown',
      modeCategory: 'Category Spend Breakdown',
      totalSpendTitle: 'Total Evaluated Spend',
      yoyGrowthTitle: 'YoY Growth',
      lineItemsTitle: 'Total Line Items',
      vendorsEvaluatedTitle: 'Vendors Evaluated'
    },
    summaryCards: {
      totalRecords: (count: number) => `${count} Total Ingested`,
      validRecords: (count: number) => `${count} Clean Records`,
      flaggedRecords: (count: number) => `${count} Anomalies Detected`,
      remediatedPct: (pct: number) => `${pct}% Remediation Rate`
    }
  },

  module2: {
    title: '4-Tier UNSPSC Taxonomy & AI Classification Engine',
    subtitle: 'Segment > Family > Class > Commodity Auto-Categorization with Confidence Scoring',
    badge: 'Module 2: AI Categorization & Taxonomy Mapping (FR-CAT-01, FR-CAT-02)',
    valuationBadge: 'INR in Crores (₹ Cr) & Column L Taxonomy',
    heading: 'AI Taxonomy Classification & Spend Year Valuation (INR Crores)',
    descriptionPrefix: 'Multi-year spend categorization by value based on ',
    descriptionHighlight: 'Column L (Commodity Codes)',
    descriptionSuffix: ' from official UNSPSC English file v260801.1 normalized via time-series FX conversion rates.',
    models: {
      enterprise: 'Enterprise QUA AI',
      public: 'Public QUA AI'
    },
    matrixTitle: 'Year-Wise Category Spend Matrix & Column L Benchmarks (INR in Crores)',
    matrixDesc: 'Annual spend progression in INR Crores (Fiscal Year: 1st April to 31st March), line item counts, and target reduction % mapped to Column L taxonomy.',
    totalEvaluated: (amount: number) => `Total Evaluated: ₹${amount.toFixed(2)} Cr`,
    matrixHeaders: {
      category: 'Procurement Category',
      colLRange: 'Column L Code Range',
      fy24: 'FY24 (₹ Cr)',
      fy25: 'FY25 (₹ Cr)',
      fy26: 'FY26 (₹ Cr)',
      total: 'Total (FY24-FY26)',
      yoyTrend: 'YoY Trend',
      targetSavings: 'Target Savings (₹ Cr)'
    },
    colLPrefix: (code: string) => `Col L: ${code}`,
    catalogTitle: 'UNSPSC Official File Catalog (Column L: Commodity Engine)',
    catalogRecordsBadge: '158,476 Catalog Records',
    catalogDescPrefix: 'Live lookup across 4-level taxonomy: Segment (Col C) ➔ Family (Col F) ➔ Class (Col I) ➔ ',
    catalogDescHighlight: 'Commodity (Column L)',
    catalogSearchPlaceholder: 'Search Column L code or commodity...',
    categories: {
      all: 'All Categories',
      packaging: 'Packaging',
      packagingMaterials: 'Packaging Materials',
      direct: 'Direct Materials',
      indirect: 'Indirect & MRO',
      logistics: 'Logistics & Freight'
    },
    workbenchTitle: 'Machine Learning Line Item Review & Column L Validation',
    workbenchDescPrefix: 'Review and confirm QUA AI 8-digit commodity taxonomy predictions converted to ',
    workbenchDescHighlight: 'INR in Crores (₹ Cr)',
    years: {
      all: 'All Years',
      y2023: '2023 (Yr 1)',
      y2024: '2024 (Yr 2)',
      y2025: '2025 (Yr 3)',
      y2026: '2026 (Yr 3)'
    },
    searchPlaceholder: 'Search description, PO, Col L...',
    lineItemHeaders: {
      lineItemYear: 'Line Item & Year',
      poDesc: 'PO & Item Description',
      vendor: 'Vendor Entity',
      unspscColL: 'UNSPSC Col L Code & Commodity',
      category: 'Category',
      spendValue: 'Spend Value (₹ Cr)',
      aiConfidence: 'AI Confidence',
      action: 'Taxonomy Action'
    },
    statusConfirmed: 'Confirmed',
    btnConfirm: 'Confirm',
    btnReassign: 'Re-Assign',
    taxonomyVerifiedFooter: 'Multi-Year Spend Taxonomy verified against Column L UNSPSC catalog',
    btnProceedToTrend: 'Proceed to 36-Month Volatility Analytics',
    coreBucketsTitle: 'Core Sourcing Buckets',
    taxonomyTreeTitle: 'UNSPSC Hierarchical Taxonomy Explorer',
    lineItemsTitle: 'Line Item AI Categorization & Review Queue',
    confidenceScore: (score: number) => `${score}% Confidence`,
    highConfidence: 'High (>= 90%)',
    mediumConfidence: 'Medium (70-89%)',
    lowConfidence: 'Low (< 70%)',
    pendingReview: 'Pending Review',
    humanVerified: 'Human Verified',
    autoApproved: 'Auto-Approved',
    reassignCategory: 'Reassign Category',
    verifyMapping: 'Verify Mapping',
    proceedToAnalytics: 'Proceed to Stage 3: Spend Analytics & Price Creep',
    filterAllBuckets: 'All Buckets',
    tableHeaders: {
      lineId: 'Line ID',
      rawText: 'Raw Purchase Description',
      vendor: 'Vendor',
      spend: 'Total Spend',
      unspscCode: 'UNSPSC Code',
      unspscTitle: 'Taxonomy Title',
      coreBucket: 'Core Bucket',
      confidence: 'AI Confidence',
      status: 'Review Status',
      action: 'Action'
    }
  },

  module3: {
    title: 'Price Creep & Volatility Leakage Analytics',
    subtitle: 'Quarter-over-quarter vendor unit price creep, contract variance, and EBITDA leakage',
    badge: 'Module 3: 36-Month Trend & Material Volatility Analysis (FR-TRD-01, FR-TRD-02)',
    valuationBadge: 'INR Crores Valuation',
    heading: 'Historical Spend & Commodity Volatility Analytics',
    description: 'Isolating true raw material market deflation from unapproved supplier price markups across a 36-month timeline in INR Crores (₹ Cr).',
    benchmarkLabel: 'Benchmark:',
    commodities: {
      icis: 'ICIS Chemicals & Resins',
      lme: 'LME Industrial Metals',
      cass: 'Cass Global Freight',
      cassIndex: 'Cass Global Freight Index',
      fastmarkets: 'Fastmarkets Paper & Pulp'
    },
    chartHeading: 'Raw Material Base Price Index vs Vendor Markup (36-Mo Horizon)',
    chartSubheading: 'Continuous 36-month timeline indexed to baseline (100.0) pegged to market indices',
    chartMarketLabel: 'Market: -4.2%',
    chartInvoicedLabel: 'Invoiced: +8.5%',
    invoicedDatasetLabel: 'Actual Vendor Invoiced Price (+8.5%)',
    marketDatasetLabel: 'Market Index Movement (-4.2%) [LME / ICIS Baseline]',
    leakageBoxTitle: 'Identified Unjustified Price Creep Leakage',
    leakageBoxDesc: 'Vendor invoices escalated despite raw material commodity deflation over 36 months.',
    varianceLeakageLabel: 'Variance Leakage',
    leakageAmountVal: '₹20.53 Cr Leakage',
    leakageUsdNote: '($2.45M USD converted @ FX rate)',
    creepAnomalyTitle: 'Creep Anomaly Detector (FR-TRD-02)',
    creepAnomalyBadge: '> 5.0% Flag',
    creepAnomalyDesc: 'Algorithms continuously monitor invoice price deltas against global benchmark indices and multi-currency FX trends.',
    avgMarkupLabel: 'Average Supplier Markup Spread',
    avgMarkupVal: '+12.7% Delta',
    avgMarkupSub: 'Above market benchmark movement',
    highCreepVendorsLabel: 'High Creep Vendors Detected',
    highCreepVendorsVal: '3 Key Suppliers',
    highCreepVendorsSub: 'Accounting for ₹17.01 Cr of total variance',
    advisoryPlayLabel: 'PROCUCEV Advisory Play:',
    advisoryPlayDesc: 'Deploy index-linked dynamic price caps in DPS NXT to automate retroactive supplier clawbacks in INR.',
    rankingsTableTitle: 'Vendor Price Volatility & Inflation Rankings (INR Crores)',
    rankingsTableDesc: 'Ranked by price variance over time with automatic >5% inflation anomaly flags converted via time-series FX rates.',
    filterAllVendors: (count: number) => `All Vendors (${count})`,
    filterCreepAnomaly: '>5% Creep Anomaly (3)',
    filterAligned: 'Aligned (1)',
    tableHeaders: {
      rank: 'Rank',
      vendor: 'Vendor Name',
      primaryCategory: 'Primary Category',
      evaluatedSpend: 'Evaluated Spend',
      priceCreep: 'Price Creep (%)',
      varianceLeakage: 'Estimated Leakage',
      riskStatus: 'Risk Status',
      action: 'Actions',
      vendorName: 'Vendor Name',
      category: 'Category',
      totalSpendInrCr: 'Total 36-Mo Spend (₹ Cr)',
      commodityBenchmark: 'Commodity Benchmark',
      priceCreepPct: 'Price Creep %',
      unjustifiedLeakage: 'Unjustified Leakage (₹ Cr)'
    },
    alignedLeakageVal: '₹0 (Aligned)',
    ctaBadge: '36-Month Volatility & Price Creep Variance fully isolated in INR Crores',
    ctaProceedButton: 'Proceed to Real-Time Savings Engine',
    vendorRankingsTitle: 'Top 5 Volatile Vendors (Price Creep Ranking)',
    spendTrendTitle: 'Multi-Year Spend Growth & Inflation Trend',
    viewTopItems: 'View Top 5 Line Items',
    volatilityIndex: (idx: number) => `Volatility Index: ${idx}`,
    priceCreepPct: (pct: number) => `+${pct}% Creep`,
    leakageAmount: (amt: string) => `${amt} Leakage`,
    proceedToSavings: 'Proceed to Stage 4: Opportunity Engine & Modules'
  },

  module4: {
    title: 'Savings Opportunity Engine & Specialized Modules',
    subtitle: 'ProCPX (Rate Contract Enforcement) & DPS NXT (Strategic Sourcing Auctions)',
    badge: 'Module 4: Real-Time Savings Engine & Optimization Targets',
    frRef: 'FR-SAV-01, FR-SAV-02',
    heading: 'Savings Engine Dashboard & Suite Integration (INR in Crores)',
    description: 'Real-time opportunity quantification denominated in INR Crores (₹ Cr) with native execution export into proCPX (e-sourcing) and DPS NXT (contract rate cards).',
    realizationTargetBadge: '16.4% Realization Target',
    heroBadge: 'Total Quantified Savings Target',
    netSpendBadge: '16.4% Net Spend',
    enterprisePotential: 'Enterprise Potential Realization',
    totalPotentialSavings: 'Total Potential EBITDA Savings Identified',
    opportunitiesCount: (count: number) => `${count} Actionable Savings Levers Identified`,
    historicalProcurementNote: (spend: number) => `Across ₹${spend.toFixed(2)} Cr evaluated historical procurement spend (multi-currency FX normalized).`,
    directSourcingLabel: 'Direct Sourcing (proCPX)',
    directSourcingVal: '₹64.71 Cr',
    contractRulesLabel: 'Contract Rules (DPS NXT)',
    contractRulesVal: '₹54.96 Cr',
    distributionTitle: 'Target vs Realized Savings Distribution (INR in Crores)',
    distributionSubtitle: 'All 4 Core Buckets Active',
    targetPrefix: (pct: string) => `Target: ${pct}`,
    categories: {
      directMaterials: 'Direct Materials',
      packagingMaterials: 'Packaging Materials',
      indirectMRO: 'Indirect & MRO',
      logisticsFreight: 'Logistics & Freight'
    },
    categoryTargets: {
      directMaterials: '18.5%',
      packagingMaterials: '16.1%',
      indirectMRO: '14.2%',
      logisticsFreight: '12.0%'
    },
    categorySavingsFound: {
      directMaterials: '₹53.80 Cr',
      packagingMaterials: '₹25.98 Cr',
      indirectMRO: '₹23.88 Cr',
      logisticsFreight: '₹16.01 Cr'
    },
    pipelineTitle: 'Identified Opportunity Pipeline & Suite Integration Triggers',
    pipelineSubtitle: 'Interactive launchers to push validated savings initiatives directly to proCPX (e-Sourcing) and DPS NXT (Rate-Card Contracts).',
    proCPXTitle: 'ProCPX Enforcement',
    proCPXSubtitle: 'Algorithmic Rate Card & Should-Cost Auditing',
    dpsNXTTitle: 'DPS NXT Sourcing',
    dpsNXTSubtitle: 'Strategic Reverse Auctions & Supplier Bidding',
    deployProCPX: 'Launch ProCPX Protocol',
    deployDPSNXT: 'Launch DPS NXT Auction',
    proceedToConversion: 'Proceed to Conversion Matrix & ROI Engine',
    filterAllModules: 'All Opportunity Types',
    filterProCPX: 'ProCPX Rate Enforcements',
    filterDPSNXT: 'DPS NXT Strategic Auctions',
    filterCategories: {
      all: 'All Categories',
      direct: 'Direct Materials',
      packaging: 'Packaging Materials',
      indirect: 'Indirect & MRO',
      logistics: 'Logistics & Freight'
    },
    filterEngines: {
      all: 'All Execution Engines',
      proCPX: 'proCPX Sourcing Engine',
      dpsNXT: 'DPS NXT Rate Enforcement'
    },
    tableHeaders: {
      oppId: 'Opportunity ID',
      lever: 'Savings Lever & Description',
      category: 'Target Category',
      vendor: 'Incumbent Supplier',
      currentSpend: 'Current Baseline Spend',
      projectedSavings: 'Projected Savings',
      savingsPct: 'Savings %',
      deploymentModule: 'Deployment Target',
      status: 'Deployment Status',
      action: 'Execute',
      oppIdAndCategory: 'Opportunity ID & Category',
      titleAndLeakage: 'Title & Contract Leakage Mechanism',
      currentSpendInrCr: 'Current Spend (₹ Cr)',
      targetPct: 'Target %',
      estSavingsInrCr: 'Est. Savings (₹ Cr)',
      suiteIntegration: 'Suite Integration',
      executionAction: 'Execution Action'
    },
    leakPrefix: (leak: string) => `Leak: ${leak}`,
    pushedBadge: 'Pushed',
    pushToProCPX: 'Push to proCPX',
    pushToDPSNXT: 'Push to DPS NXT',
    ctaSubtitle: 'Ready to calculate Client ROI and Transition to Commercial Lock-in Funnel',
    ctaProceedButton: 'Proceed to Conversion Matrix & ROI Engine'
  },

  module5: {
    title: 'Client Sign-Off & EBITDA Savings Conversion Matrix',
    subtitle: 'Adjust realization probability sliders, simulate lock-in, and generate final client deliverable',
    badge: 'Screen 5: Executive Conversion Matrix & Commercial SaaS Portal',
    badgeSubtitle: 'Advisory-to-SaaS Value Lifecycle',
    heading: 'Commercial Realization & SaaS Lock-in Matrix (FR-MTRX-01, FR-MTRX-02)',
    generateExecutiveReport: 'Generate Executive Brief',
    description: 'Bridging high-impact diagnostic consulting engagements into sticky, multi-year recurring enterprise SaaS contracts in INR Crores (₹ Cr).',
    generateBrief: 'Generate Executive Brief',
    funnelTitle: 'Client Conversion Funnel & SaaS Value Lifecycle',
    funnelSubtitle: 'The 3-phase strategic roadmap driving 3x faster conversion from diagnostic advisory to long-term SaaS ARR across ₹732.41 Cr evaluated spend.',
    conversionViewBadge: 'Conversion View',
    funnelHeaders: {
      funnelPhase: 'Funnel Phase',
      actionableFocus: 'Platform Actionable Focus',
      valueOutcome: 'Value Outcome Delivered',
      commercialMetric: 'Commercial Lock-In Metric'
    },
    calculatorTitle: 'Executive ROI & SaaS Payback Calculator (INR in Crores)',
    interactiveModelBadge: 'Interactive Model',
    annualSpendLabel: 'Evaluated Annual Spend (INR)',
    annualSpendVal: (spend: number) => `₹${spend.toFixed(2)} Crores`,
    minSpend: '₹100 Cr',
    midSpend: '₹1,250 Cr',
    maxSpend: '₹2,500 Cr',
    targetSavingsRateLabel: 'Target Savings Rate Identified',
    savingsRateVal: (rate: number) => `${rate.toFixed(1)}%`,
    conservativeLabel: '8.0% (Conservative)',
    frdBenchmarkLabel: '16.4% (FRD Benchmark)',
    aggressiveLabel: '25.0% (Aggressive)',
    platformFeeLabel: 'PROCUCEV Platform Engine Fee',
    platformFeeVal: (feeRate: number, feeCr: number) => `${feeRate.toFixed(2)}% of spend (₹${feeCr.toFixed(2)} Cr/yr)`,
    projectedCommercialRealization: 'Projected Commercial Realization (INR in Crores)',
    grossAnnualizedSavings: 'Gross Annualized Savings',
    grossSavingsCrVal: (savings: number) => `₹${savings.toFixed(2)} Cr`,
    acrossCoreBuckets: 'Across 4 core buckets',
    netClientBenefit: 'Net Client Benefit',
    netBenefitCrVal: (benefit: number) => `₹${benefit.toFixed(2)} Cr`,
    afterPlatformFee: 'After platform SaaS fee',
    clientRoiMultiple: 'Client ROI Multiple',
    roiMultipleVal: (roi: number) => `${roi.toFixed(1)}x`,
    estimatedPayback: 'Estimated Payback',
    paybackMonthsVal: (months: number) => `~${months.toFixed(1)} Months`,
    lockInButton: 'Lock In Multi-Year SaaS Commercial Terms',
    lockInSimulatorTitle: 'Client EBITDA Realization Matrix',
    lockInSimulatorSubtitle: 'Fine-tune realization sliders per initiative and commit EBITDA impact',
    simulateLockIn: 'Simulate Lock-In Commitment',
    generatingDeliverable: 'Generating Deliverable...',
    lockInCommitted: 'EBITDA Lock-In Committed!',
    exportReport: 'Export Final Advisory Report',
    summaryCards: {
      grossSavings: 'Gross Opportunity Identified',
      netCommittedSavings: 'Net Committed EBITDA Savings',
      averageConfidence: 'Confidence-Weighted Realization',
      paybackPeriod: 'Implementation Payback Period'
    },
    sliders: {
      proCPXSlider: 'ProCPX Rate Card Enforcement Realization',
      dpsNXTSlider: 'DPS NXT Strategic Sourcing Auction Realization',
      vendorConsolidationSlider: 'Vendor Consolidation & Volume Tier Realization'
    }
  },

  modals: {
    clientSetup: {
      title: 'Client & Dataset Ingestion Setup',
      subtitle: 'Define ERP data source profile, fiscal year parameters, and base currency',
      stepBadge: 'Step 1: Multi-Currency Setup (INR in Crores)',
      moduleBadge: 'Module 1 (3-Year Intake)',
      enterpriseClientName: 'Enterprise Client Name',
      clientName: 'Client / Enterprise Name',
      clientPlaceholder: 'e.g. Apex Industrial Dynamics (Fortune 500)',
      quickSelect: 'Quick Select:',
      selectDatasetType: 'Select Ingestion Dataset Type',
      datasetType: 'Dataset Type',
      invoiceData: 'Invoice Data',
      trialBalance: 'Trial Balance',
      vendorSpend: 'Vendor Spend',
      contractSchedule: 'Contract Schedule',
      baseCurrency: 'Base Currency',
      timePeriod: 'Time Period',
      selectedBadge: 'SELECTED',
      datasetOptions: {
        purchaseHistory: {
          id: 'Purchase History',
          title: 'Purchase History',
          badge: 'PO Master & Line Items',
          desc: 'Purchase orders, item descriptions, line quantities, supplier master IDs, and agreed unit rates across 36 months.'
        },
        invoiceData: {
          id: 'Invoice Data',
          title: 'Invoice Data',
          badge: 'AP Invoices & Scans',
          desc: 'Accounts payable invoices, OCR scanned receipts, billed line items, tax breakdowns, and payment disbursement records.'
        },
        trialBalance: {
          id: 'Trial Balance',
          title: 'Trial Balance',
          badge: 'GL & Cost Centers',
          desc: 'General ledger trial balance, chart of accounts, cost center allocations, and financial journal entries.'
        }
      },
      historicalEvaluationWindow: 'Historical Evaluation Window',
      spendPeriods: {
        months36: '36 Months (FY24 - FY26: 1 Apr 2023 - 31 Mar 2026)',
        months24: '24 Months (FY25 - FY26: 1 Apr 2024 - 31 Mar 2026)',
        months12: '12 Months (FY26: 1 Apr 2025 - 31 Mar 2026)'
      },
      baseNormalizationCurrency: 'Base Normalization Currency',
      inrButtonLabel: '₹ INR (Cr)',
      operatingRegion: 'Enterprise Operating Region',
      regions: {
        global: 'GLOBAL Multi-Region',
        na: 'North America (NA)',
        eu: 'European Union (EU)',
        apac: 'Asia-Pacific (APAC)'
      },
      estimatedSpendLabel: 'Estimated 3-Yr Spend (INR Crores)',
      spendFormatted: (cr: number) => `₹${cr.toFixed(2)} Cr`,
      fxGuaranteeNote: 'AI uses time-series FX conversion rates (USD/INR @ ₹83.8, EUR/INR @ ₹91.4, GBP/INR @ ₹106.5) to normalize all line items into INR in Crores (₹ Cr).',
      liveFxBadge: 'Live FX',
      cancel: 'Cancel',
      saveAndRun: 'Save & Run Normalization',
      submitBtn: 'Confirm & Proceed to Upload Data'
    },
    fixCurrency: {
      title: 'Normalize Multi-Currency to INR in Crores',
      subtitle: 'Normalize transaction amounts using authoritative RBI/ECB exchange rate benchmarks',
      fxEngineBadge: 'Multi-Currency FX Engine',
      recordIdLabel: 'Record ID & Year:',
      poNumberLabel: 'PO Number:',
      vendorCategoryLabel: 'Vendor & Category:',
      rawAmountLabel: 'Raw Invoice Amount:',
      detectedCurrency: 'Detected Currency:',
      detectedCurrencyLabel: 'Detected Invoice Currency',
      reportedAmount: 'Reported Amount:',
      targetCurrency: 'Target Currency:',
      targetCurrencyINR: 'INR (₹ Indian Rupee)',
      conversionRateLabel: 'Conversion Rate:',
      convertedValueLabel: 'Converted Value in Crores:',
      cancel: 'Cancel',
      applyConversion: 'Apply FX Conversion to INR'
    },
    mergeVendor: {
      title: 'Merge Disparate Supplier Entities',
      subtitle: 'Map ERP subsidiary vendor spelling into canonical supplier master entity',
      entityDisambiguationBadge: 'Entity Disambiguation',
      incomingEntityLabel: 'Incoming Unmapped Entity:',
      selectTargetLabel: 'Select Target Master Supplier ID',
      targetNameLabel: 'Target Raw Vendor Name:',
      canonicalMasterLabel: 'Master Canonical Vendor:',
      canonicalHint: 'Transactions under this vendor alias will be consolidated into the master record.',
      cancel: 'Cancel',
      confirmMerge: 'Map to Master Supplier'
    },
    reassign: {
      title: 'Modify Column L Commodity Code',
      subtitle: 'Update UNSPSC taxonomy mapping and assigned procurement category',
      catalogBadge: 'UNSPSC Official Catalog (Column L)',
      recordsCountBadge: '158k+ Records',
      targetLineItemLabel: 'Target Line Item:',
      searchPlaceholder: 'Search Column L code or commodity description...',
      lineItemLabel: 'Line Item:',
      currentCategory: 'Current Category:',
      selectCategory: 'Select Target Category:',
      selectBucket: 'Select Core Sourcing Bucket:',
      cancel: 'Cancel',
      saveMapping: 'Apply Column L Mapping'
    },
    topItems: {
      categoryRank: (rank: number) => `Rank #${rank} Category`,
      vendorRank: (rank: number) => `Rank #${rank} Supplier`,
      unspscCommodity: (code: string) => `UNSPSC Commodity: ${code}`,
      masterVendorId: (id: string) => `Master ID: ${id}`,
      spendShare: (pct: string) => `${pct}% of Total Spend`,
      spendShareVendor: (pct: string) => `${pct}% Spend Share`,
      categoryTitle: (cat: string) => `${cat} — Top 10 Line Items & 3-Year Price Trends`,
      vendorTitle: (vendor: string) => `${vendor} — Top Line Items & 3-Year Price Trends`,
      fiscalYearNote: 'Fiscal Year: 1st April to 31st March (FY24 / FY25 / FY26) • Mapped to uploaded procurement dataset.',
      vendorFiscalYearNote: (category: string, code: string) => `Primary Segment: ${category} (UNSPSC: ${code}) • Fiscal Years: FY24 / FY25 / FY26 (1st Apr to 31st Mar).`,
      exportCSV: 'Export CSV',
      totalCategorySpend: 'Total Category Spend',
      totalVendorSpend: 'Total Vendor Spend',
      activeLineItems: 'Active Line Items',
      contractedItems: 'Contracted Items',
      priceCreepRiskItems: 'Price Creep Risk Items',
      itemsCount: (count: number) => `${count} Items`,
      lineItemsCount: (count: number) => `${count.toLocaleString()} Line Items`,
      activeItemsCount: (count: number) => `${count.toLocaleString()} Items`,
      quantifiedSavingsPotential: 'Quantified Savings Potential',
      negotiationOpportunity: 'Negotiation Opportunity',
      highCreepBadge: '(▲ >15%)',
      searchPlaceholderCategory: 'Search items, vendor, UNSPSC code, or PO...',
      searchPlaceholderVendor: 'Search items, UNSPSC code, or PO...',
      trendFilter: 'Trend Filter:',
      filterAllTop10: 'All Top 10',
      filterAllItems: 'All Items',
      filterHighCreep: 'High Creep (▲ >15%)',
      filterSteady: 'Steady (<10%)',
      tableHeaders: {
        itemId: '# Item ID',
        description: 'Item Description & UNSPSC Col L',
        vendorPO: 'Vendor Entity & PO',
        poRef: 'PO Reference',
        annualQty: 'Annual Qty',
        fy24Price: 'FY24 Price',
        fy25Price: 'FY25 Price',
        fy26Price: 'FY26 Price',
        fy24Title: '1st April 2023 – 31st March 2024',
        fy25Title: '1st April 2024 – 31st March 2025',
        fy26Title: '1st April 2025 – 31st March 2026',
        priceTrend3Yr: '3-Yr Price Trend',
        spend3Yr: '3-Yr Spend (₹ Cr)',
        savingsPotential: 'Savings Potential',
        savingsOpportunity: 'Savings Opportunity'
      },
      noItemsMatch: 'No line items match the filter criteria.',
      unspscColL: (code: string) => `UNSPSC Col L: ${code}`,
      standardOpportunity: 'Standard',
      lakhsVal: (lakhs: number) => `₹${lakhs} Lakhs`,
      priceTrendFormulaNote: 'Price Trend Formula: Line Item 3-Yr Spend = ∑ (Order Quantity × Net Price × Currency in INR).',
      vendorSpendFormulaNote: 'Vendor Spend Formula: Line Item 3-Yr Spend = ∑ (Order Quantity × Net Price × Currency in INR).',
      baseNormalizationNote: 'Base Normalization: INR in Crores (₹ Cr)',
      showingCategoryItems: (shown: number, total: number, category: string) => `Showing ${shown} of ${total} items in ${category}`,
      showingVendorItems: (shown: number, total: number, vendor: string) => `Showing ${shown} of ${total} items purchased from ${vendor}`,
      closePopUp: 'Close Pop-up'
    },
    proCPX: {
      title: 'proCPX Integration',
      subtitle: 'e-Sourcing Event Creator',
      heading: 'Launch Sourcing Event',
      deployedSuccess: 'e-Sourcing Event Launched to proCPX!',
      deployedDesc: (oppId: string, count: number, savings: string) => `RFx event ID RFX-2026-${oppId} has been created with ${count} suppliers invited and a target savings goal of ${savings}.`,
      targetOpportunityLabel: 'Selected Savings Lever:',
      targetVendorLabel: 'Target Supplier:',
      identifiedVariance: 'Identified Rate Card Variance:',
      recoveryProtocolLabel: 'Enforcement Protocol:',
      identifiedSavings: 'Identified Savings',
      rootCause: 'Root Cause:',
      sourcingMechanism: 'Sourcing Mechanism',
      mechanisms: {
        multiStageRFP: 'Multi-Stage RFP & e-Bidding',
        reverseAuction: 'Real-Time English Reverse Auction',
        sealedBid: 'Sealed Bid Benchmark Competition'
      },
      targetBaselineLabel: 'Target Savings Baseline (USD)',
      supplierCohortLabel: (count: number) => `Pre-Qualified Supplier Cohort (${count})`,
      addSupplier: '+ Add Supplier',
      verifiedVendor: 'Verified Vendor',
      complianceNote: 'proCPX enforces automated multi-round price reduction with strict SLA compliance and multi-tier pricing brackets.',
      cancel: 'Cancel',
      dismiss: 'Dismiss',
      deploying: 'Deploying to proCPX...',
      pushButton: 'Push to proCPX',
      launchButton: 'Push to proCPX'
    },
    dpsNXT: {
      title: 'DPS NXT Integration',
      subtitle: 'Multi-Round Dynamic Bidding, Reverse Auction & Supplier Allocation Engine',
      sublabel: 'Rate Card & Contract Rules Engine',
      heading: 'Automate Rate Card & Contract Rules',
      deployedSuccess: 'Rate-Card Enforcement Deployed to DPS NXT!',
      deployedDesc: (title: string, amount: string) => `Automated rate guardrails active for ${title}. Locking in ${amount} in annualized recurring savings.`,
      targetCategoryLabel: 'Sourcing Category:',
      auctionFormatLabel: 'Auction Format:',
      targetSavings: 'Target Recurring Savings',
      recommendedAction: 'Recommended Action:',
      maxPriceCreepCap: 'Max Allowed Price Creep Cap',
      percentMax: '% max',
      commodityIndexPegging: 'Commodity Index Pegging',
      benchmarks: {
        lme: 'LME & ICIS Official Benchmark',
        platts: 'Platts Petrochemical Index',
        cass: 'Cass Freight Transportation Benchmark',
        cassShort: 'Cass Freight Benchmark',
        ppi: 'PPI Producer Price Index (Govt)',
        ppiShort: 'PPI Producer Price Index'
      },
      rules: {
        invoicePriceMatch: 'Automatic In-Line Invoice PO Price Match',
        autoRejectBenchmark: 'Auto-Reject Invoices exceeding Benchmark Index',
        rebateTier: 'Volume Rebate Tier Auto-Calculation',
        statusActive: 'ACTIVE',
        statusEnabled: 'ENABLED',
        statusEnforced: 'ENFORCED',
        statusOff: 'OFF'
      },
      securityNote: 'DPS NXT digitally seals the contract amendments with ERP two-way sync (SAP S/4HANA & Oracle ERP Cloud).',
      qualifiedBiddersCount: (n: number) => `${n} Qualified Bidders Invited`,
      enforcedBtn: 'ENFORCED',
      offBtn: 'OFF',
      cancel: 'Cancel',
      enforcing: 'Enforcing in DPS NXT...',
      pushButton: 'Push to DPS NXT'
    },
    report: {
      docRef: 'Doc Reference: FRD-PRC-2026-V2 | Confidential',
      title: 'Executive Advisory Diagnostic & ROI Blueprint (INR in Crores)',
      subtitle: 'Board-Level Strategic Spend Diagnostic, Vendor Leakage & Sourcing Roadmaps',
      printPdf: 'Print / PDF',
      platformTitle: 'PROCUCEV PLATFORM ENGINE',
      platformSubtitle: 'Strategic Procurement Advisory & AI Savings Realization Deliverable',
      date: 'Date: August 12, 2026',
      author: 'Author: Srinivas Mukku (Co-Founder & CEO)',
      baseCurrency: 'Base Currency: INR in Crores (₹ Cr)',
      enterpriseClient: 'Enterprise Client:',
      evaluatedSpendWindow: 'Evaluated Spend Window:',
      spendWindowVal: '36 Months (Multi-Currency)',
      totalAnalyzedSpend: 'Total Analyzed Spend:',
      totalAnalyzedSpendVal: (spend: number) => `₹${spend.toFixed(2)} Crores`,
      overallRealization: 'Overall Realization:',
      overallRealizationVal: '16.4% Net Target',
      kpiTotalSavings: 'Total Savings',
      totalSavingsVal: (savings: number) => `₹${savings.toFixed(2)} Cr`,
      totalSavingsSub: '16.4% of Total Spend',
      kpiPriceCreep: 'Price Creep Leak',
      priceCreepVal: '₹20.53 Cr',
      priceCreepSub: 'Unjustified vs Market Index',
      kpiConversionVelocity: 'Conversion Velocity',
      conversionVelocityVal: '3x',
      conversionVelocitySub: 'Advisory to SaaS Lock-in',
      kpiAiConfidence: 'AI Confidence',
      aiConfidenceVal: '98.4%',
      aiConfidenceSub: 'Enterprise QUA Model',
      section1Title: '1. Category Spend & Target Savings Distribution (INR in Crores)',
      tableHeaders: {
        category: 'Core Spend Category',
        baseline: 'Baseline Spend (₹ Cr)',
        targetPct: 'Benchmark Target %',
        savings: 'Quantified Savings (₹ Cr)',
        engine: 'Execution Engine'
      },
      section2Title: '2. Actionable Sourcing & Contract Execution Pipeline (INR in Crores)',
      recommendedPrefix: 'Recommended: ',
      leakTypePrefix: ' | Leak Type: ',
      savingsTarget: 'Savings Target',
      savingsTargetVal: (cr: number) => `₹${cr.toFixed(2)} Cr`,
      advisoryLeadership: 'PROCUCEV Advisory Leadership',
      ceoName: 'Srinivas Mukku, Co-Founder & CEO',
      documentGenerated: 'Document generated via PROCUCEV Platform Engine',
      diagnosticValidated: 'Diagnostic Engagement: 100% Validated',
      close: 'Close Window',
      downloadPDF: 'Download Official PDF'
    }
  },

  toasts: {
    runningAiCat: 'Running Enterprise QUA AI Categorization & Taxonomy Mapping...',
    transitioningToVolatility: 'Transitioning to 36-Month Volatility Analytics...',
    launchingSavings: 'Launching Real-Time Savings Opportunity Engine...',
    openingConversion: 'Opening Commercial Realization & SaaS Lock-in Portal...',
    pushedToProCPX: (oppId: string) => `Opportunity ${oppId} successfully pushed to proCPX Sourcing Engine.`,
    deployedToDPSNXT: (oppId: string) => `Rate cards & index pegging deployed to DPS NXT for Opportunity ${oppId}.`,
    recordNormalized: (recordId: string, curr: string) => `Record ${recordId} normalized to base currency ${curr} (Reconciled in Spend Analytics)`,
    recordMapped: (recordId: string, masterVendorId: string) => `Record ${recordId} mapped to Master Supplier: ${masterVendorId} (Reconciled in Spend Analytics)`,
    blanketFixesApplied: '⚡ Blanket AI Fixes Applied: 100% of vendor entities & currency rates reconciled under INR Crores (₹732.41 Cr)',
    validationReset: 'Validation records reset to initial pre-check state (2 pending anomalies).',
    batchUploadSpend: (fileName: string, spendCr: number, recordsCount: number) => `Calculated total spend for "${fileName}": ₹${spendCr.toFixed(2)} Cr across ${recordsCount.toLocaleString()} records [Order Qty × Net Price × FX].`,
    unspscConfirmed: (mappingId: string) => `UNSPSC mapping ${mappingId} confirmed and locked into QUA taxonomy.`,
    taxonomyReassigned: (code: string, bucket: string) => `Taxonomy re-assigned to UNSPSC ${code} (${bucket}).`
  },

  errors: {
    titles: {
      validation: 'Input Validation Failed',
      network: 'Network Connection Interrupted',
      auth: 'Authentication Required',
      notFound: 'Resource Not Found',
      conflict: 'Data Conflict Detected',
      server: 'Internal System Failure',
      rateLimit: 'Request Limit Exceeded',
      generic: 'Operation Could Not Be Completed'
    },
    validation: {
      requiredField: (fieldName: string) => `Field "${fieldName}" is required and cannot be left blank.`,
      invalidFormat: (fieldName: string, expectedFormat: string) => `Field "${fieldName}" has an invalid format. Expected format: ${expectedFormat}.`,
      outOfRange: (fieldName: string, min: number | string, max: number | string) => `Field "${fieldName}" must be between ${min} and ${max}.`,
      actionableAdvice: 'Please review highlighted input fields, correct any invalid values, and re-submit the form.'
    },
    network: {
      offline: 'You appear to be offline. Network requests cannot be dispatched until connectivity is restored.',
      timeout: (operation: string, ms: number) => `The request for "${operation}" timed out after ${ms}ms due to poor latency.`,
      unreachable: (service: string) => `Unable to establish connection to ${service}. The service may be temporarily down or undergoing maintenance.`,
      actionableAdvice: 'Check your internet connection, verify that the backend server is running on the configured port, and click Retry.'
    },
    auth: {
      sessionExpired: 'Your security session has expired or the token is invalid.',
      insufficientPermissions: (role: string, requiredRole: string) => `Current role "${role}" lacks permission. Required privilege: "${requiredRole}".`,
      tenantAccessDenied: (tenantId: string) => `Access denied to tenant workspace "${tenantId}". Please verify your organization credentials.`,
      actionableAdvice: 'Please re-authenticate or contact your system administrator to request access credentials.'
    },
    notFound: {
      entityNotFound: (entityType: string, id: string) => `The requested ${entityType} with identifier "${id}" could not be found in the database.`,
      actionableAdvice: 'The item may have been recently deleted or reassigned. Please refresh your data view or select an existing record.'
    },
    conflict: {
      duplicateEntity: (entityType: string, key: string) => `A ${entityType} with "${key}" already exists in the system.`,
      concurrencyConflict: 'Another user or process has updated this record simultaneously.',
      actionableAdvice: 'Reload the latest data before applying modifications, or specify a unique identifier to avoid collisions.'
    },
    server: {
      internalError: (statusCode: number, requestId: string) => `Server returned HTTP ${statusCode}. Diagnostic tracking reference: ${requestId}.`,
      databaseUnavailable: 'The primary database service failed to respond to the transaction query.',
      actionableAdvice: 'Our engineering logs have captured this incident. Please quote the diagnostic tracking reference when contacting enterprise support.'
    },
    rateLimit: {
      throttled: (retryAfterSec: number) => `API rate limit exceeded. Too many requests in a short interval. Please wait ${retryAfterSec}s before retrying.`,
      actionableAdvice: 'Pause automated scripts or high-frequency clicks to allow quota replenishment.'
    }
  }
} as const;

