import { describe, it, expect } from 'vitest';
import {
  PRODUCTION_PILOT_STATUS,
  HIGH_IMPACT_SPEND_THRESHOLD,
  PCBI_PRODUCTION_PILOT_BASE_PERIOD,
  PCBI_PRODUCTION_PILOT_BASE_INDEX,
  PRODUCTION_PILOT_GOVERNANCE_LOCKS,
  DATA_CONSISTENCY_BASELINE,
  ACCEPTANCE_TEST_24_DEFINITIONS
} from '../../src/constants/pcbiProductionPilot';

describe('PCBI Production Pilot Constants (Backend)', () => {
  it('should define module 3 status as PRODUCTION_PILOT_READY', () => {
    expect(PRODUCTION_PILOT_STATUS).toBe('PRODUCTION_PILOT_READY');
    expect(HIGH_IMPACT_SPEND_THRESHOLD).toBe(10000000);
    expect(PCBI_PRODUCTION_PILOT_BASE_PERIOD).toBe('2020-04');
    expect(PCBI_PRODUCTION_PILOT_BASE_INDEX).toBe(100.0);
  });

  it('should enforce production governance locks', () => {
    expect(PRODUCTION_PILOT_GOVERNANCE_LOCKS.MODULE1_FROZEN).toBe(true);
    expect(PRODUCTION_PILOT_GOVERNANCE_LOCKS.MODULE2_FROZEN).toBe(true);
    expect(PRODUCTION_PILOT_GOVERNANCE_LOCKS.PCBI_MASTER_IMMUTABLE).toBe(true);
    expect(PRODUCTION_PILOT_GOVERNANCE_LOCKS.MODULE4_DISCONNECTED).toBe(true);
    expect(PRODUCTION_PILOT_GOVERNANCE_LOCKS.SAVINGS_CALCULATED).toBe(0);
    expect(PRODUCTION_PILOT_GOVERNANCE_LOCKS.COMMERCIAL_PURCHASES).toBe(0);
  });

  it('should verify data consistency baseline values', () => {
    expect(DATA_CONSISTENCY_BASELINE.CUSTOMER_COMMODITY_COUNT).toBe(13);
    expect(DATA_CONSISTENCY_BASELINE.MATERIAL_COMMODITY_COUNT).toBe(12);
    expect(DATA_CONSISTENCY_BASELINE.EXCLUDED_SERVICE_COUNT).toBe(1);
    expect(DATA_CONSISTENCY_BASELINE.PRODUCTION_READY_COUNT).toBe(6);
    expect(DATA_CONSISTENCY_BASELINE.RESEARCH_QUEUE_COUNT).toBe(6);
    expect(DATA_CONSISTENCY_BASELINE.PARTIAL_HISTORY_COUNT).toBe(2);
    expect(DATA_CONSISTENCY_BASELINE.NO_HISTORY_COUNT).toBe(2);
    expect(DATA_CONSISTENCY_BASELINE.TOTAL_CUSTOMER_SPEND).toBe(86317055);
  });

  it('should define all 24 acceptance test definitions', () => {
    expect(ACCEPTANCE_TEST_24_DEFINITIONS).toHaveLength(24);
    expect(ACCEPTANCE_TEST_24_DEFINITIONS[0].testId).toBe('TEST_01');
    expect(ACCEPTANCE_TEST_24_DEFINITIONS[23].testId).toBe('TEST_24');
  });
});
