/**
 * Backend Log Diagnostics & Automated Error Resolution Constants
 */

export const LOG_DIAGNOSTIC_SEVERITIES = ['error', 'warn'] as const;

export const DIAGNOSTIC_ERROR_CATEGORIES = [
  'VALIDATION_ERROR',
  'DATABASE_ERROR',
  'NETWORK_ERROR',
  'AUTH_ERROR',
  'INTERNAL_ERROR',
  'UNKNOWN_ERROR',
] as const;

export const DEFAULT_MAX_PARSE_LINES = 1000;

export const AUTO_RESOLVE_ACTIONS = {
  RETRY: 'RETRY',
  VALIDATE_INPUT: 'VALIDATE_INPUT',
  INVALIDATE_CACHE: 'INVALIDATE_CACHE',
  CHECK_DB_CONNECTION: 'CHECK_DB_CONNECTION',
  CHECK_CREDENTIALS: 'CHECK_CREDENTIALS',
  INVESTIGATE_UNHANDLED: 'INVESTIGATE_UNHANDLED',
} as const;
