/**
 * PCBI Module 3 — Business Validation & Commodity Population Mode Constants
 */

import type {
  PCBIResearchGapQueueItem,
  PCBIMultiSourceRecord
} from '../types/pcbiCommodityCoverage';

export const MODULE_3_SOFTWARE_STATUS = 'PRODUCTION_READY_DYNAMIC_PCBI' as const;
export const DATA_OPERATING_MODE = 'CONTINUOUS_COMMODITY_EXPANSION' as const;
export const NEXT_DEVELOPMENT_PHASE = 'ONLY_DEFECT_DRIVEN' as const;
export const DEVELOPMENT_MODE = 'DEFECT_DRIVEN_ONLY' as const;
export const NEXT_BUSINESS_ACTIVITY = 'PCBI_DATA_RESEARCH_AND_ADMIN_POPULATION' as const;
export const NEXT_ACTIVITY = 'PCBI_DATA_RESEARCH_AND_ADMIN_POPULATION' as const;

export const INITIAL_COMMODITY_GAP_QUEUE: PCBIResearchGapQueueItem[] = [
  {
    commodityId: 'COM-MET-FMO',
    commodityName: 'Ferro Molybdenum 65%',
    module2Classification: 'METALS_AND_ALLOYS',
    unspsc: '30102900',
    customerSpend: 12500000,
    customerSpendCr: '₹1.25 Cr',
    transactionCount: 65,
    pcbiId: 'PCBI-IND-MET-FMO-001',
    pcbiDefinitionStatus: 'DEFINED',
    pcbiDataStatus: 'NO_HISTORY',
    requiredStartDate: '2020-04-01',
    requiredEndDate: '2026-06-30',
    requiredFrequency: 'WEEKLY',
    requiredUnit: 'INR/MT',
    requiredCurrency: 'INR',
    requiredGeography: 'INDIA_DOMESTIC',
    availableHistory: '0 months (None)',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    materiality: 'HIGH',
    priority: 'P1 — Critical Coverage Gap',
    adminAction: 'SEARCH / ADD SOURCE',
    researchStatus: 'QUEUED',
    dateAdded: '2026-09-01T00:00:00.000Z',
    lastUpdated: '2026-09-28T16:00:00.000Z'
  },
  {
    commodityId: 'COM-EQP-SLP',
    commodityName: 'Heavy Duty Slurry Pumps',
    module2Classification: 'INDUSTRIAL_MACHINERY',
    unspsc: '40151500',
    customerSpend: 10320000,
    customerSpendCr: '₹1.03 Cr',
    transactionCount: 28,
    pcbiId: 'PCBI-IND-EQP-SLP-001',
    pcbiDefinitionStatus: 'DEFINED',
    pcbiDataStatus: 'NO_HISTORY',
    requiredStartDate: '2020-04-01',
    requiredEndDate: '2026-06-30',
    requiredFrequency: 'MONTHLY',
    requiredUnit: 'INR/UNIT',
    requiredCurrency: 'INR',
    requiredGeography: 'INDIA_DOMESTIC',
    availableHistory: '0 months (None)',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    materiality: 'HIGH',
    priority: 'P1 — Critical Coverage Gap',
    adminAction: 'SEARCH / ADD SOURCE',
    researchStatus: 'QUEUED',
    dateAdded: '2026-09-01T00:00:00.000Z',
    lastUpdated: '2026-09-28T16:00:00.000Z'
  },
  {
    commodityId: 'COM-MET-TCI',
    commodityName: 'Tungsten Carbide Inserts',
    module2Classification: 'TOOLS_AND_MACHINERY',
    unspsc: '23241600',
    customerSpend: 7680000,
    customerSpendCr: '₹0.77 Cr',
    transactionCount: 142,
    pcbiId: 'PCBI-IND-MET-TCI-001',
    pcbiDefinitionStatus: 'DEFINED',
    pcbiDataStatus: 'PARTIAL_HISTORY',
    requiredStartDate: '2020-04-01',
    requiredEndDate: '2026-06-30',
    requiredFrequency: 'MONTHLY',
    requiredUnit: 'INR/PIECE',
    requiredCurrency: 'INR',
    requiredGeography: 'INDIA_DOMESTIC',
    availableHistory: '42 months (2023-01 to 2026-06)',
    sourceStatus: 'VALIDATED',
    methodologyStatus: 'APPROVED',
    materiality: 'MEDIUM',
    priority: 'P2 — High Coverage Gap',
    adminAction: 'UPLOAD PRE-2023 DATA',
    researchStatus: 'SOURCE_IDENTIFIED',
    dateAdded: '2026-09-01T00:00:00.000Z',
    lastUpdated: '2026-09-28T16:00:00.000Z'
  },
  {
    commodityId: 'COM-PLM-HDP',
    commodityName: 'HDPE Injection Molding Granules',
    module2Classification: 'POLYMERS_AND_PLASTICS',
    unspsc: '13111000',
    customerSpend: 3040000,
    customerSpendCr: '₹0.30 Cr',
    transactionCount: 115,
    pcbiId: 'PCBI-IND-PLM-HDP-001',
    pcbiDefinitionStatus: 'DEFINED',
    pcbiDataStatus: 'PARTIAL_HISTORY',
    requiredStartDate: '2020-04-01',
    requiredEndDate: '2026-06-30',
    requiredFrequency: 'MONTHLY',
    requiredUnit: 'INR/KG',
    requiredCurrency: 'INR',
    requiredGeography: 'INDIA_DOMESTIC',
    availableHistory: '42 months (2023-01 to 2026-06)',
    sourceStatus: 'VALIDATED',
    methodologyStatus: 'APPROVED',
    materiality: 'MEDIUM',
    priority: 'P3 — Medium Coverage Gap',
    adminAction: 'UPLOAD PRE-2023 DATA',
    researchStatus: 'SOURCE_IDENTIFIED',
    dateAdded: '2026-09-01T00:00:00.000Z',
    lastUpdated: '2026-09-28T16:00:00.000Z'
  },
  {
    commodityId: 'COM-STL-SCR',
    commodityName: 'Stainless Steel 304 Scrap',
    module2Classification: 'METALS_AND_ALLOYS',
    unspsc: '30103000',
    customerSpend: 2980000,
    customerSpendCr: '₹0.30 Cr',
    transactionCount: 84,
    pcbiId: 'PCBI-IND-STL-SCR-001',
    pcbiDefinitionStatus: 'DEFINED',
    pcbiDataStatus: 'SOURCE_UNVERIFIED',
    requiredStartDate: '2020-04-01',
    requiredEndDate: '2026-06-30',
    requiredFrequency: 'MONTHLY',
    requiredUnit: 'INR/MT',
    requiredCurrency: 'INR',
    requiredGeography: 'INDIA_DOMESTIC',
    availableHistory: '75 months (2020-04 to 2026-06)',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'APPROVED',
    materiality: 'MEDIUM',
    priority: 'P3 — Medium Coverage Gap',
    adminAction: 'VERIFY COMMERCIAL TERMS',
    researchStatus: 'IN_PROGRESS',
    dateAdded: '2026-09-01T00:00:00.000Z',
    lastUpdated: '2026-09-28T16:00:00.000Z'
  },
  {
    commodityId: 'COM-LUB-HYD',
    commodityName: 'Industrial Hydraulic Oil ISO 68',
    module2Classification: 'FUELS_AND_LUBRICANTS',
    unspsc: '15121500',
    customerSpend: 1939325,
    customerSpendCr: '₹0.19 Cr',
    transactionCount: 50,
    pcbiId: 'PCBI-IND-LUB-HYD-001',
    pcbiDefinitionStatus: 'DEFINED',
    pcbiDataStatus: 'SPECIFICATION_MISMATCH',
    requiredStartDate: '2020-04-01',
    requiredEndDate: '2026-06-30',
    requiredFrequency: 'MONTHLY',
    requiredUnit: 'INR/LTR',
    requiredCurrency: 'INR',
    requiredGeography: 'INDIA_DOMESTIC',
    availableHistory: '75 months (2020-04 to 2026-06)',
    sourceStatus: 'VALIDATED',
    methodologyStatus: 'APPROVED',
    materiality: 'LOW',
    priority: 'P4 — Low Coverage Gap',
    adminAction: 'APPROVE SPECIFICATION MAPPING',
    researchStatus: 'SOURCE_IDENTIFIED',
    dateAdded: '2026-09-01T00:00:00.000Z',
    lastUpdated: '2026-09-28T16:00:00.000Z'
  }
];

export const PCBI_MULTI_SOURCES_REGISTRY: Record<string, PCBIMultiSourceRecord[]> = {
  'COM-MET-FMO': [
    {
      sourceId: 'SRC-FMO-01-GOV',
      sourceName: 'Indian Bureau of Mines (IBM) Monthly Bulletin',
      sourceType: 'GOVERNMENT',
      url: 'https://ibm.gov.in/index.php/page/monthly-bulletin',
      document: 'IBM_Mineral_Price_June2026.pdf',
      publisher: 'Indian Bureau of Mines, Ministry of Mines',
      publicationDate: '2026-07-15',
      checksum: '4b3d8816a3f9e4e2d31215a782bcf291a1829e92d4b8f521b44ecb958c89a01f',
      frequency: 'MONTHLY',
      unit: 'INR/MT',
      currency: 'INR',
      geography: 'INDIA_DOMESTIC',
      sourceStatus: 'UNDER_EVALUATION'
    },
    {
      sourceId: 'SRC-FMO-02-PUB',
      sourceName: 'Fastmarkets Ferro-Alloys Weekly Assessment',
      sourceType: 'COMMERCIAL',
      url: 'https://www.fastmarkets.com/commodity/ferro-alloys/ferro-molybdenum',
      document: 'Fastmarkets_Moly_Weekly_202606.xlsx',
      publisher: 'Fastmarkets Metals & Mining',
      publicationDate: '2026-06-28',
      checksum: '9f83c1264b39e2f81014e8b392a831e51241f8a846c91350a8276f759a2245b1',
      frequency: 'WEEKLY',
      unit: 'USD/KG',
      currency: 'USD',
      geography: 'GLOBAL_CFR_INDIA',
      sourceStatus: 'UNVERIFIED'
    },
    {
      sourceId: 'SRC-FMO-03-IND',
      sourceName: 'All India Ferro Alloys Association (AIFAA)',
      sourceType: 'INDUSTRY_ASSOCIATION',
      url: 'https://www.aifaa.org/market-data',
      document: 'AIFAA_Quarterly_Review_Q2_2026.pdf',
      publisher: 'All India Ferro Alloys Association',
      publicationDate: '2026-07-02',
      checksum: '1e4c92b8429e7150a82759a21245b14b3d8816a3f9e4e2d31215a782bcf291a1',
      frequency: 'MONTHLY',
      unit: 'INR/MT',
      currency: 'INR',
      geography: 'INDIA_DOMESTIC',
      sourceStatus: 'UNDER_EVALUATION'
    }
  ]
};
