/**
 * PCBI Commodity Data Lab — Initial Queue and Sources Fixtures
 */

import type {
  CommodityResearchQueueRow,
  CommoditySourceEvidenceObject
} from '../types/pcbiCommodityDataLab';

export const INITIAL_COMMODITY_RESEARCH_QUEUE: CommodityResearchQueueRow[] = [
  {
    commodity: 'Ferro Molybdenum 65%',
    commodityId: 'COM-MET-FMO',
    module2Classification: 'METALS_AND_ALLOYS',
    unspsc: '30102900',
    customerSpend: 12500000,
    customerSpendCr: '₹1.25 Cr',
    transactionCount: 65,
    pcbiId: 'PCBI-FEMO-65-001',
    seriesId: 'SER-IND-FEMO-65-M',
    currentStatus: 'PARTIAL_HISTORY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '18 observations / 32 months (Under Review)',
    requiredFrequency: 'WEEKLY',
    availableFrequency: 'MONTHLY',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P1 — Critical Coverage Gap',
    researchStatus: 'IN_PROGRESS',
    lastUpdated: '2026-09-28T18:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Heavy Duty Slurry Pumps',
    commodityId: 'COM-EQP-SLP',
    module2Classification: 'INDUSTRIAL_MACHINERY',
    unspsc: '40151500',
    customerSpend: 10320000,
    customerSpendCr: '₹1.03 Cr',
    transactionCount: 28,
    pcbiId: 'PCBI-IND-EQP-SLP-001',
    seriesId: 'SER-IND-EQP-SLP-M',
    currentStatus: 'NO_HISTORY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '0 months (None)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'NONE',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P1 — Critical Coverage Gap',
    researchStatus: 'QUEUED',
    lastUpdated: '2026-09-28T16:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Tungsten Carbide Inserts',
    commodityId: 'COM-MET-TCI',
    module2Classification: 'TOOLS_AND_MACHINERY',
    unspsc: '27112800',
    customerSpend: 8500000,
    customerSpendCr: '₹0.85 Cr',
    transactionCount: 42,
    pcbiId: 'PCBI-IND-MET-TCI-001',
    seriesId: 'SER-IND-MET-TCI-M',
    currentStatus: 'NO_HISTORY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '0 months (None)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'NONE',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P2 — High Coverage Gap',
    researchStatus: 'QUEUED',
    lastUpdated: '2026-09-28T16:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Caustic Soda Lye 48%',
    commodityId: 'COM-CHM-CSL',
    module2Classification: 'CHEMICALS_AND_GASES',
    unspsc: '12352300',
    customerSpend: 6500000,
    customerSpendCr: '₹0.65 Cr',
    transactionCount: 19,
    pcbiId: 'PCBI-IND-CHM-CSL-001',
    seriesId: 'SER-IND-CHM-CSL-M',
    currentStatus: 'PRODUCTION_READY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '75 months (Complete)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'MONTHLY',
    sourceStatus: 'SOURCE_VERIFIED',
    methodologyStatus: 'METHODOLOGY_APPROVED',
    priority: 'P4 — Low Coverage Gap',
    researchStatus: 'RESOLVED',
    lastUpdated: '2026-09-28T12:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Hot Rolled Steel Coils IS 2062',
    commodityId: 'COM-STEEL-HRC',
    module2Classification: 'METALS_AND_ALLOYS',
    unspsc: '30101804',
    customerSpend: 6667825,
    customerSpendCr: '₹0.67 Cr',
    transactionCount: 1,
    pcbiId: 'PCBI-IND-STL-HRC-001',
    seriesId: 'SER-IND-STL-HRC-W',
    currentStatus: 'PRODUCTION_READY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '75 months (Complete)',
    requiredFrequency: 'WEEKLY',
    availableFrequency: 'WEEKLY',
    sourceStatus: 'SOURCE_VERIFIED',
    methodologyStatus: 'METHODOLOGY_APPROVED',
    priority: 'P4 — Low Coverage Gap',
    researchStatus: 'RESOLVED',
    lastUpdated: '2026-09-28T12:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Linear Alkyl Benzene (LAB)',
    commodityId: 'COM-CHM-LAB',
    module2Classification: 'CHEMICALS_AND_GASES',
    unspsc: '12352100',
    customerSpend: 5400000,
    customerSpendCr: '₹0.54 Cr',
    transactionCount: 12,
    pcbiId: 'PCBI-IND-CHM-LAB-001',
    seriesId: 'SER-IND-CHM-LAB-M',
    currentStatus: 'PRODUCTION_READY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '75 months (Complete)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'MONTHLY',
    sourceStatus: 'SOURCE_VERIFIED',
    methodologyStatus: 'METHODOLOGY_APPROVED',
    priority: 'P4 — Low Coverage Gap',
    researchStatus: 'RESOLVED',
    lastUpdated: '2026-09-28T12:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Liquid Chlorine 99.5%',
    commodityId: 'COM-CHM-CHL',
    module2Classification: 'CHEMICALS_AND_GASES',
    unspsc: '12352000',
    customerSpend: 4200000,
    customerSpendCr: '₹0.42 Cr',
    transactionCount: 14,
    pcbiId: 'PCBI-IND-CHM-CHL-001',
    seriesId: 'SER-IND-CHM-CHL-M',
    currentStatus: 'PARTIAL_HISTORY',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '45 months',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'MONTHLY',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P2 — High Coverage Gap',
    researchStatus: 'IN_PROGRESS',
    lastUpdated: '2026-09-28T15:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Welding Electrodes E7018',
    commodityId: 'COM-MET-WEL',
    module2Classification: 'TOOLS_AND_MACHINERY',
    unspsc: '23271810',
    customerSpend: 3800000,
    customerSpendCr: '₹0.38 Cr',
    transactionCount: 51,
    pcbiId: 'PCBI-IND-MET-WEL-001',
    seriesId: 'SER-IND-MET-WEL-M',
    currentStatus: 'MISSING',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '0 months (Unmapped)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'NONE',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P2 — High Coverage Gap',
    researchStatus: 'QUEUED',
    lastUpdated: '2026-09-28T16:00:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'Hydraulic Oil ISO VG 68',
    commodityId: 'COM-OIL-HYD',
    module2Classification: 'LUBRICANTS_AND_FUELS',
    unspsc: '15121500',
    customerSpend: 3500000,
    customerSpendCr: '₹0.35 Cr',
    transactionCount: 33,
    pcbiId: 'PCBI-IND-OIL-HYD-001',
    seriesId: 'SER-IND-OIL-HYD-M',
    currentStatus: 'FREQUENCY_MISMATCH',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '75 months (Quarterly)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'QUARTERLY',
    sourceStatus: 'SOURCE_VERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P3 — Medium Coverage Gap',
    researchStatus: 'QUEUED',
    lastUpdated: '2026-09-28T14:30:00.000Z',
    action: 'OPEN WORKSPACE'
  },
  {
    commodity: 'MS Seamless Pipes Heavy Wall',
    commodityId: 'COM-STEEL-PIP',
    module2Classification: 'METALS_AND_ALLOYS',
    unspsc: '40171501',
    customerSpend: 2900000,
    customerSpendCr: '₹0.29 Cr',
    transactionCount: 8,
    pcbiId: 'PCBI-IND-STL-PIP-001',
    seriesId: 'SER-IND-STL-PIP-M',
    currentStatus: 'SPECIFICATION_MISMATCH',
    requiredHistory: '75 months (2020-04 to 2026-06)',
    availableHistory: '40 months (Light Wall)',
    requiredFrequency: 'MONTHLY',
    availableFrequency: 'MONTHLY',
    sourceStatus: 'SOURCE_UNVERIFIED',
    methodologyStatus: 'METHODOLOGY_PENDING',
    priority: 'P3 — Medium Coverage Gap',
    researchStatus: 'QUEUED',
    lastUpdated: '2026-09-28T13:00:00.000Z',
    action: 'OPEN WORKSPACE'
  }
];

export const INITIAL_COMMODITY_SOURCES: Record<string, CommoditySourceEvidenceObject[]> = {
  'COM-MET-FMO': [
    {
      sourceId: 'SRC-FMO-MMR-01',
      sourceName: 'Minerals & Metals Review Weekly Assessment',
      publisher: 'Binani Commercial Co. / MMR',
      url: 'https://www.mmronline.com/archives',
      documentName: 'MMR_FeMo60_Historical_Assessments_2021_2024.pdf',
      publicationDate: '2024-04-15',
      uploadDate: '2026-09-28T16:30:00.000Z',
      fileType: 'PDF',
      checksum: 'sha256-a9f87c2b5e4d1f0a3c7b9e8d6a5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c',
      geography: 'India Domestic Ex-Works',
      gradeSpecification: 'Ferro Molybdenum 60% Mo Basis',
      unit: 'INR/KG',
      currency: 'INR',
      frequency: 'MONTHLY',
      deliveryBasis: 'Ex-Works / Basic Price',
      historicalCoverage: '18 observations (2021-01 to 2024-04)',
      extractionStatus: 'EXTRACTED',
      validationStatus: 'ISSUES_DETECTED',
      methodologyStatus: 'PENDING',
      approvalStatus: 'UNDER_REVIEW',
      extractedObservationsCount: 18
    },
    {
      sourceId: 'SRC-FMO-STEELMINT-02',
      sourceName: 'BigMint / SteelMint Indian Ferro Alloy Monitor',
      publisher: 'BigMint India Technologies',
      url: 'https://www.bigmint.co/prices/ferro-alloys',
      documentName: 'BigMint_FeMo60_DailyWeekly_2024_2026.csv',
      publicationDate: '2026-06-30',
      uploadDate: '2026-09-28T16:45:00.000Z',
      fileType: 'CSV',
      checksum: 'sha256-c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2',
      geography: 'India Domestic (Mumbai / Raipur / Nagpur)',
      gradeSpecification: 'FeMo 60% Grade',
      unit: 'INR/KG',
      currency: 'INR',
      frequency: 'WEEKLY',
      deliveryBasis: 'FOR Destination',
      historicalCoverage: '2024-01 to 2026-06',
      extractionStatus: 'EXTRACTED',
      validationStatus: 'ISSUES_DETECTED',
      methodologyStatus: 'PENDING',
      approvalStatus: 'UNDER_REVIEW',
      extractedObservationsCount: 26
    },
    {
      sourceId: 'SRC-FMO-FASTMARKETS-03',
      sourceName: 'Fastmarkets / Metal Bulletin European FeMo 65%',
      publisher: 'Fastmarkets MB London',
      url: 'https://www.fastmarkets.com/commodities/minor-metals/molybdenum',
      documentName: 'Fastmarkets_FeMo65_Rotterdam_DDP.xlsx',
      publicationDate: '2026-06-25',
      uploadDate: '2026-09-28T17:00:00.000Z',
      fileType: 'XLSX',
      checksum: 'sha256-f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e2',
      geography: 'Europe (Rotterdam Basis)',
      gradeSpecification: 'Ferro Molybdenum 65% Min Mo',
      unit: 'USD/KG_MO',
      currency: 'USD',
      frequency: 'WEEKLY',
      deliveryBasis: 'DDP Rotterdam',
      historicalCoverage: '2020-04 to 2026-06 (75 months)',
      extractionStatus: 'EXTRACTED',
      validationStatus: 'VALIDATED',
      methodologyStatus: 'PENDING',
      approvalStatus: 'UNDER_REVIEW',
      extractedObservationsCount: 75
    }
  ]
};
