/**
 * PCBI Ferro Molybdenum 65% Research Candidate — Observations Part A (OBS-001 to OBS-010)
 */

import type { FeMoObservationRecord } from '../types/pcbiFeMoResearch';

export const RAW_FEMO_RESEARCH_OBSERVATIONS_PART_A: FeMoObservationRecord[] = [
  // FeMo 60% Indian Reference Observations (Category 2)
  {
    observationId: 'OBS-FEMO-001',
    sourceDate: '2020-03-06',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 1210,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 1210000,
    provenanceHash: '8b7fa120e64cd46820200306mmr60',
    sourceUrl: 'https://www.scribd.com/document/879380846/MMRW09-03-2020',
    notes: 'Weekly basic price Mumbai table'
  },
  {
    observationId: 'OBS-FEMO-002',
    sourceDate: '2021-01-01',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 1250,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai/Raipur, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 1250000,
    provenanceHash: '4a6bc89102ef11020210101mmr60',
    sourceUrl: 'https://next.airfaas.com/dms/REST/objects/0/93177/1/files/131226/content',
    notes: 'Ex-works Raipur/Mumbai weekly quote'
  },
  {
    observationId: 'OBS-FEMO-003',
    sourceDate: '2021-10-01',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2130,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2130000,
    provenanceHash: '9f10ca23bcde45020211001mmr60',
    sourceUrl: 'https://next.airfaas.com/dms/REST/objects/0/93177/1/files/131226/content',
    notes: 'Sharp molybdenum raw concentrate surge worldwide'
  },
  {
    observationId: 'OBS-FEMO-004',
    sourceDate: '2021-11-19',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2200,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2200000,
    provenanceHash: '1e4c92b8429e7150a82759a21245b14b',
    sourceUrl: 'https://next.airfaas.com/dms/REST/objects/0/93177/1/files/131226/content',
    notes: 'Domestic alloy maker spot quote'
  },
  {
    observationId: 'OBS-FEMO-005',
    sourceDate: '2021-12-03',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2300,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2300000,
    provenanceHash: '7a12b3c4d5e6f70820211203mmr60',
    sourceUrl: 'https://next.airfaas.com/dms/REST/objects/0/93177/1/files/131226/content',
    notes: 'End of year inventory restocking'
  },
  {
    observationId: 'OBS-FEMO-006',
    sourceDate: '2023-02-10',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 4575,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 4575000,
    provenanceHash: '699209508mmrw13022023femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Historical peak driven by global supply disruption'
  },
  {
    observationId: 'OBS-FEMO-007',
    sourceDate: '2023-09-08',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 3500,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 3500000,
    provenanceHash: '3500000mmr20230908femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Market normalization post-peak'
  },
  {
    observationId: 'OBS-FEMO-008',
    sourceDate: '2024-01-25',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2900,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2900000,
    provenanceHash: '2900000mmr20240125femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Q1 alloy manufacturing rate'
  },
  {
    observationId: 'OBS-FEMO-009',
    sourceDate: '2024-05-03',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2700,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2700000,
    provenanceHash: '2700000mmr20240503femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Stable domestic demand'
  },
  {
    observationId: 'OBS-FEMO-010',
    sourceDate: '2024-05-17',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2950,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2950000,
    provenanceHash: '2950000mmr20240517femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Mid-month adjustment'
  }
];
