/**
 * PCBI Ferro Molybdenum 65% Research Candidate — Observations Part B (OBS-011 to OBS-020)
 */

import type { FeMoObservationRecord } from '../types/pcbiFeMoResearch';

export const RAW_FEMO_RESEARCH_OBSERVATIONS_PART_B: FeMoObservationRecord[] = [
  {
    observationId: 'OBS-FEMO-011',
    sourceDate: '2024-11-22',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2700,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2700000,
    provenanceHash: '2700000mmr20241122femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Post-Diwali trading'
  },
  {
    observationId: 'OBS-FEMO-012',
    sourceDate: '2024-12-06',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2710,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2710000,
    provenanceHash: '2710000mmr20241206femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Year-end assessment'
  },
  {
    observationId: 'OBS-FEMO-013',
    sourceDate: '2025-02-14',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2720,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2720000,
    provenanceHash: '2720000mmr20250214femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Q1 2025 benchmark'
  },
  {
    observationId: 'OBS-FEMO-014',
    sourceDate: '2025-02-21',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2750,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2750000,
    provenanceHash: '2750000mmr20250221femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Weekly domestic adjustment'
  },
  {
    observationId: 'OBS-FEMO-015',
    sourceDate: '2025-07-18',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 2850,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 2850000,
    provenanceHash: '2850000mmr20250718femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Monsoon season trade'
  },
  {
    observationId: 'OBS-FEMO-016',
    sourceDate: '2025-08-08',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 3300,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 3300000,
    provenanceHash: '3300000mmr20250808femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Imported concentrate spike'
  },
  {
    observationId: 'OBS-FEMO-017',
    sourceDate: '2025-08-15',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 60%',
    rawValue: 3200,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Mumbai, India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_OBSERVATION',
    inrPerMtDirectEquivalent: 3200000,
    provenanceHash: '3200000mmr20250815femo60',
    sourceUrl: 'https://www.scribd.com/document/699209508/MMRW13-02-2023',
    notes: 'Consolidation around 3200'
  },
  {
    observationId: 'OBS-FEMO-018',
    sourceDate: '2026-07-22',
    sourceName: 'BigMint / SteelMint reporting',
    publisher: 'BigMint Technologies Ltd',
    sourceGrade: 'FeMo 60%',
    rawValue: 4260,
    rawUnit: 'INR/kg',
    rawCurrency: 'INR',
    geography: 'Ex-works India',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_60_INDIAN_REFERENCE',
    evidenceStatus: 'PUBLIC_REPORTED',
    inrPerMtDirectEquivalent: 4260000,
    provenanceHash: '4260000bigmint20260722femo60',
    sourceUrl: 'https://www.bigmint.co/ferroalloy',
    notes: 'Assessed as ₹4,260/kg basic ex-works domestic Indian basis'
  },

  // FeMo 65–70% International Reference Observations (Category 3)
  {
    observationId: 'OBS-FEMO-019',
    sourceDate: '2020-03-09',
    sourceName: 'Minerals & Metals Review',
    publisher: 'Minerals & Metals Review (MMR)',
    sourceGrade: 'FeMo 65–70%',
    rawValue: 16.5,
    rawUnit: 'USD/kg Mo',
    rawCurrency: 'USD',
    geography: 'International (DP Rotterdam)',
    frequency: 'Weekly',
    evidenceCategory: 'FEMO_65_70_INTERNATIONAL_REFERENCE',
    evidenceStatus: 'REFERENCE_ONLY',
    inrPerMtDirectEquivalent: null,
    provenanceHash: '165usdkgmo20200309mmrint',
    sourceUrl: 'https://www.scribd.com/document/879380846/MMRW09-03-2020',
    notes: 'International market table reference; not directly convertible without import parity methodology'
  },
  {
    observationId: 'OBS-FEMO-020',
    sourceDate: '2021-11-30',
    sourceName: 'Argus Metals sample report',
    publisher: 'Argus Media group',
    sourceGrade: 'FeMo 65–70%',
    rawValue: 44.3,
    rawUnit: 'USD/kg Mo',
    rawCurrency: 'USD',
    geography: 'DP Rotterdam',
    frequency: 'Daily',
    evidenceCategory: 'FEMO_65_70_INTERNATIONAL_REFERENCE',
    evidenceStatus: 'REFERENCE_ONLY',
    inrPerMtDirectEquivalent: null,
    provenanceHash: '443usdkgmo20211130argusmet',
    sourceUrl: 'https://view.argusmedia.com/rs/584-BUW-606/images/MET-Sample-Report-Argus-Metals-International-301121.pdf',
    notes: 'European warehouse pricing; basis and grade distinct from Indian domestic ex-works'
  }
];
