/**
 * Subscription, Entitlement & Activation Constants (Prompt 288)
 */

import { SUBSCRIPTION_TIERS } from './auth';

export { SUBSCRIPTION_TIERS };

export const SUBSCRIPTION_STATES = {
  FREE: 'FREE',
  PENDING_ACTIVATION: 'PENDING_ACTIVATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
} as const;

export const COMMERCIAL_STATUS = {
  FREE_TIER: 'FREE_TIER',
  QUOTED: 'QUOTED',
  INVOICED: 'INVOICED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  COMPLETED: 'COMPLETED'
} as const;

export const FEATURE_PERMISSIONS = {
  REGISTRATION: 'REGISTRATION',
  LOGIN: 'LOGIN',
  DATA_UPLOAD: 'DATA_UPLOAD',
  SPEND_SUMMARY: 'SPEND_SUMMARY',
  SPEND_DETAIL: 'SPEND_DETAIL',
  SUPPLIER_SUMMARY: 'SUPPLIER_SUMMARY',
  SUPPLIER_OPPORTUNITY: 'SUPPLIER_OPPORTUNITY',
  ITEM_LEVEL_OPPORTUNITY: 'ITEM_LEVEL_OPPORTUNITY',
  CATEGORY_SUMMARY: 'CATEGORY_SUMMARY',
  CATEGORY_OPPORTUNITY: 'CATEGORY_OPPORTUNITY',
  PLANT_SUMMARY: 'PLANT_SUMMARY',
  PRICE_DISPERSION_SUMMARY: 'PRICE_DISPERSION_SUMMARY',
  PRICE_DISPERSION_FULL: 'PRICE_DISPERSION_FULL',
  SAVINGS_INDICATOR: 'SAVINGS_INDICATOR',
  TOTAL_SAVINGS: 'TOTAL_SAVINGS',
  SAVINGS_BY_CATEGORY_BROAD: 'SAVINGS_BY_CATEGORY_BROAD',
  SAVINGS_BY_CATEGORY_DETAILED: 'SAVINGS_BY_CATEGORY_DETAILED',
  SAVINGS_BY_SUPPLIER: 'SAVINGS_BY_SUPPLIER',
  MODULE_2_SUMMARY: 'MODULE_2_SUMMARY',
  MODULE_2_FULL: 'MODULE_2_FULL',
  MODULE_3_SUMMARY: 'MODULE_3_SUMMARY',
  MODULE_3_FULL: 'MODULE_3_FULL',
  PCBI_SUMMARY: 'PCBI_SUMMARY',
  PCBI_DETAIL: 'PCBI_DETAIL',
  BENCHMARK_SUMMARY: 'BENCHMARK_SUMMARY',
  BENCHMARK_SOURCE_DETAIL: 'BENCHMARK_SOURCE_DETAIL',
  MODULE_4_SUMMARY: 'MODULE_4_SUMMARY',
  MODULE_4_FULL: 'MODULE_4_FULL',
  SAVINGS_WATERFALL_SUMMARY: 'SAVINGS_WATERFALL_SUMMARY',
  SAVINGS_WATERFALL_FULL: 'SAVINGS_WATERFALL_FULL',
  SAVINGS_REALIZATION_SUMMARY: 'SAVINGS_REALIZATION_SUMMARY',
  SAVINGS_REALIZATION_FULL: 'SAVINGS_REALIZATION_FULL',
  ACTION_TRACKER: 'ACTION_TRACKER',
  MANAGEMENT_QUICK_SUMMARY: 'MANAGEMENT_QUICK_SUMMARY',
  BOARDROOM_EVIDENCE_SUMMARY: 'BOARDROOM_EVIDENCE_SUMMARY',
  BOARDROOM_EVIDENCE_FULL: 'BOARDROOM_EVIDENCE_FULL',
  PDF_EXPORT_SUMMARY: 'PDF_EXPORT_SUMMARY',
  PDF_EXPORT_FULL: 'PDF_EXPORT_FULL',
  PPTX_EXPORT_SUMMARY: 'PPTX_EXPORT_SUMMARY',
  PPTX_EXPORT_FULL: 'PPTX_EXPORT_FULL',
  DETAILED_DATA_EXPORT: 'DETAILED_DATA_EXPORT',
  ADMIN_SUBSCRIPTION_MANAGEMENT: 'ADMIN_SUBSCRIPTION_MANAGEMENT'
} as const;

export const SUBSCRIPTION_AUDIT_ACTIONS = {
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_PROVISIONED: 'SUBSCRIPTION_PROVISIONED',
  OTP_REQUESTED: 'OTP_REQUESTED',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_FAILED: 'OTP_FAILED',
  ACTIVATION_CODE_GENERATED: 'ACTIVATION_CODE_GENERATED',
  ACTIVATION_EMAIL_SENT: 'ACTIVATION_EMAIL_SENT',
  ACTIVATION_ATTEMPTED: 'ACTIVATION_ATTEMPTED',
  ACTIVATION_SUCCEEDED: 'ACTIVATION_SUCCEEDED',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_UPGRADED: 'SUBSCRIPTION_UPGRADED',
  SUBSCRIPTION_DOWNGRADED: 'SUBSCRIPTION_DOWNGRADED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_SUSPENDED: 'SUBSCRIPTION_SUSPENDED',
  SUBSCRIPTION_REACTIVATED: 'SUBSCRIPTION_REACTIVATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED'
} as const;

export const SUBSCRIPTION_CONFIG = {
  ACTIVATION_CODE_EXPIRY_MS: 72 * 60 * 60 * 1000, // 72 hours
  ACTIVATION_MAX_ATTEMPTS: 5,
  ADMIN_OTP_EXPIRY_MS: 10 * 60 * 1000, // 10 minutes
  ADMIN_OTP_MAX_ATTEMPTS: 5,
  CODE_PREFIX: 'PCV-'
} as const;

export const SUBSCRIPTION_MESSAGES = {
  FEATURE_LOCKED: 'This feature requires a higher subscription tier. Contact Procucev for upgrade.',
  ACTIVATION_REQUIRED: 'Subscription activation required. Please enter your emailed activation code.',
  OTP_REQUIRED: 'Admin mobile OTP verification required for this action.',
  OTP_EXPIRED: 'Admin OTP has expired. Please request a new OTP.',
  OTP_INVALID: 'Invalid Admin OTP entered. Please check and try again.',
  OTP_MAX_ATTEMPTS: 'Maximum Admin OTP verification attempts exceeded.',
  ACTIVATION_CODE_EXPIRED: 'Activation code has expired. Please contact Procucev administrator.',
  ACTIVATION_CODE_INVALID: 'Invalid activation code entered.',
  ACTIVATION_CODE_USED: 'This activation code has already been used.',
  ACTIVATION_CODE_LOCKED: 'Activation code locked due to excessive failed attempts.',
  ACTIVATION_SUCCESS: 'Subscription successfully activated. Welcome to your upgraded tier!',
  PROVISION_SUCCESS: 'Subscription successfully provisioned. Activation code dispatched.',
  RENEW_SUCCESS: 'Subscription successfully renewed.',
  STATUS_UPDATED: 'Subscription status updated successfully.',
  ADMIN_ONLY: 'Access denied: Subscription management is restricted to authorized administrators.',
  TENANT_MISMATCH: 'Access denied: You do not have permission to access another tenant\'s data.'
} as const;

export const BRONZE_ENTITLED_FEATURES = new Set<string>([
  FEATURE_PERMISSIONS.REGISTRATION,
  FEATURE_PERMISSIONS.LOGIN,
  FEATURE_PERMISSIONS.DATA_UPLOAD,
  FEATURE_PERMISSIONS.SPEND_SUMMARY,
  FEATURE_PERMISSIONS.SUPPLIER_SUMMARY,
  FEATURE_PERMISSIONS.CATEGORY_SUMMARY,
  FEATURE_PERMISSIONS.PLANT_SUMMARY,
  FEATURE_PERMISSIONS.SAVINGS_INDICATOR,
  FEATURE_PERMISSIONS.PDF_EXPORT_SUMMARY
]);

export const SILVER_ENTITLED_FEATURES = new Set<string>([
  ...BRONZE_ENTITLED_FEATURES,
  FEATURE_PERMISSIONS.SPEND_DETAIL,
  FEATURE_PERMISSIONS.CATEGORY_OPPORTUNITY,
  FEATURE_PERMISSIONS.PRICE_DISPERSION_SUMMARY,
  FEATURE_PERMISSIONS.TOTAL_SAVINGS,
  FEATURE_PERMISSIONS.SAVINGS_BY_CATEGORY_BROAD,
  FEATURE_PERMISSIONS.MODULE_2_SUMMARY,
  FEATURE_PERMISSIONS.MODULE_3_SUMMARY,
  FEATURE_PERMISSIONS.PCBI_SUMMARY,
  FEATURE_PERMISSIONS.BENCHMARK_SUMMARY,
  FEATURE_PERMISSIONS.MODULE_4_SUMMARY,
  FEATURE_PERMISSIONS.SAVINGS_WATERFALL_SUMMARY,
  FEATURE_PERMISSIONS.SAVINGS_REALIZATION_SUMMARY,
  FEATURE_PERMISSIONS.MANAGEMENT_QUICK_SUMMARY,
  FEATURE_PERMISSIONS.BOARDROOM_EVIDENCE_SUMMARY,
  FEATURE_PERMISSIONS.PPTX_EXPORT_SUMMARY
]);

export const GOLD_ENTITLED_FEATURES = new Set<string>([
  ...SILVER_ENTITLED_FEATURES,
  FEATURE_PERMISSIONS.SUPPLIER_OPPORTUNITY,
  FEATURE_PERMISSIONS.ITEM_LEVEL_OPPORTUNITY,
  FEATURE_PERMISSIONS.PRICE_DISPERSION_FULL,
  FEATURE_PERMISSIONS.SAVINGS_BY_CATEGORY_DETAILED,
  FEATURE_PERMISSIONS.SAVINGS_BY_SUPPLIER,
  FEATURE_PERMISSIONS.MODULE_2_FULL,
  FEATURE_PERMISSIONS.MODULE_3_FULL,
  FEATURE_PERMISSIONS.PCBI_DETAIL,
  FEATURE_PERMISSIONS.BENCHMARK_SOURCE_DETAIL,
  FEATURE_PERMISSIONS.MODULE_4_FULL,
  FEATURE_PERMISSIONS.SAVINGS_WATERFALL_FULL,
  FEATURE_PERMISSIONS.SAVINGS_REALIZATION_FULL,
  FEATURE_PERMISSIONS.ACTION_TRACKER,
  FEATURE_PERMISSIONS.BOARDROOM_EVIDENCE_FULL,
  FEATURE_PERMISSIONS.PDF_EXPORT_FULL,
  FEATURE_PERMISSIONS.PPTX_EXPORT_FULL,
  FEATURE_PERMISSIONS.DETAILED_DATA_EXPORT
]);
